### ISSUE TITLE
Manage Karaoke DB - not updating

### ISSUE THREAD

**Issue by altere987** [OpenKJ/OpenKJ#100]
Running Linux Mint 18.3
OpenKJ 1.3.85 will not Update the Karaoke DB. It goes through all the motions and everything appears to be successful but the DB was actually never updated.

I had to roll back to stable 1.2.18 to update the DB again. I upgraded to 1.3.85 again and have tried several things from closing the program, removing the directory and re-adding, rebooting, etc. and 1.3.85 won't update my DB.

**Comment by coyote1357** [comment]
This should be fixed now.  You caught unstable mid-rewrite on the db update code, which was necessitated by changes in Qt 5.11 that affected sqlite access in multithreaded applications.
