### ISSUE TITLE
Feature/Enhancement - Incoming Requests

### ISSUE THREAD

**Issue by altere987** [OpenKJ/OpenKJ#101]
When an incoming request comes in under someone that's already in rotation, it matches fine. When a new singer signs up and the request comes in and doesn't match current singers, can we have it auto selected to New Singer rather then Existing?

**Comment by altere987** [comment]
Additionally, I use a hotspot at some places and when you turn the hotspot off and stop accepting requests it still polls the server with an error message. Can we get a "Don't show this again" after say 2-5 minutes. It was popping up several times throughout my last 1 1/2 hr playing.

**Comment by coyote1357** [comment]
I'll implement the first as soon as I get 1.4 stable released and the current feature freeze is over.

On the second, I'll figure out a clean way to make it be less annoying.  Btw, as a workaround, you can go into settings and untick the use request server checkbox to make it stop polling completely.

**Comment by backstagekaraoke** [comment]
already implemented.
