### ISSUE TITLE
Feature Request: Add Shuffle for Break music

### ISSUE THREAD

**Issue by TallPatrick** [OpenKJ/OpenKJ#102]
As a user, I would like to be able to have my break music play in a semi-random order throughout the night so that I don't have to manually ensure I don't play the same break music all the time.

**Comment by backstagekaraoke** [comment]
@TallPatrick yeah true, would be handy .... 

In the meantime, you could make a copy of your break music tracks into a separate folder, and just use bulk rename utility (or similar) to add a prefix at the beginning that randomizes each track, so essentially they will be imported 'in a random order'

i.e at the moment it would be:

Artist 1 - Song 1
Artist 1 - Song 2
Artist 1 - Song 3
Artist 1 - Song 4
Artist 2 - Song 1
Artist 2 - Song 2
Artist 2 - Song 3
Artist 2 - Song 4
Artist 3 - Song 1
Artist 3 - Song 2
Artist 3 - Song 3
Artist 3 - Song 4

becomes

%randomprefix% - Artist 1 - Song 1
%randomprefix% - Artist 2 - Song 3
%randomprefix% - Artist 3 - Song 8
%randomprefix% - Artist 4 - Song 4
%randomprefix% - Artist 7 - Song 12
%randomprefix% - Artist 9 - Song 3

etc etc

a bit of work, but should get you by for now

**Comment by backstagekaraoke** [comment]
There is now a randomize function for break music as of 1.8
