### ISSUE TITLE
Theme & Settings Issue

### ISSUE THREAD

**Issue by altere987** [OpenKJ/OpenKJ#107]
With Linux Mint, once OpenKJ is loaded if I switch to a different workspace and load a browser then go back to the workspace OpenKJ is loaded in, the theme goes to completely white and Audio, Video, Network, and Other disappears from the Settings menu. I've had to close OpenKJ and reload to resolve the issue.

This is an intermittent issue as it doesn't happen every time.
1.5.2

**Comment by coyote1357** [comment]
This one may be tough to track down and fix.  The theme stuff OpenKJ is using is just part of the normal Qt theming functionality, so this may be a bug in the underlying toolkit.

**Comment by coyote1357** [comment]
Settings was reworked completely to not use the left menu, so that part shouldn't be a problem anymore.  I've never been able to duplicate the broken theme issue.  I'm going to close this for now.  It can be reopened if it rears its ugly head again.

**Comment by altere987** [comment]
The theme going to complete white still happens and has been an ongoing problem. I haven't tried settings when this happens anymore as I normally just close OpenKJ and reload it at that point. Switching to another workspace and back doesn't seem to do this, only when loading up chrome from another workspace and then going back to the OpenKJ workspace. 

If there's anything else I can provide to help you reproduce or track down the problem, let me know.
