### ISSUE TITLE
brackets in audio filename breaks zipping

### ISSUE THREAD

**Issue by generalredneck** [OpenKJ/OpenKJ#110]
On my zip files that have square brackets `]` or `[` in them I get the following error message
![image](https://user-images.githubusercontent.com/526491/49323312-101cb000-f4df-11e8-8606-70d18f256bbc.png)
Since the majority of my files have the song ID in square brackets, that makes the majority of them fail to load... I don't remember this being the case last Feb when I was KJing for my company party. 

I suspect that the error is happening somewhere here: https://github.com/OpenKJ/OpenKJ/blob/0b0af667d5acfea8895a329157db6a2e9547c057/OpenKJ/okarchive.cpp#L239-L276

It sounds like an escaping issue... but not sure.

**Comment by generalredneck** [comment]
FYI incase you are wondering... The way I tested it was the square backets is I remove the square brackets from the zip's filename and the cdg and mp3 file inside and all worked well.

**Comment by generalredneck** [comment]
A bit more information. I'm running Ubuntu 18.04 OpenKJ Version: 1.4.5 stable Built: Nov 28 2018 04:47:09

**Comment by generalredneck** [comment]
Ok wrote up a quick script to rename all my zipfiles to not have square brackets and still be a version I could parse and got it up and running for now. I don't know how to compile C++ very well these days or I would help you debug this thing... haven't touched it in almost 20 years.

**Comment by coyote1357** [comment]
Fixed this in 1.5.13 unstable.  If you still have any around with the brackets, give it a shot.

**Comment by generalredneck** [comment]
I'll validate it when 1.5.13 unstable comes in through launchpad... I've not figured out building from source yet on bionic.

**Comment by generalredneck** [comment]
Worked like a champ.
