### ISSUE TITLE
Not saving the background image on restart

### ISSUE THREAD

**Issue by backstagekaraoke** [OpenKJ/OpenKJ#111]
- Upon quitting OpenKJ, its doesn't load the specified background image, it loads the default OpenKJ graphic. 
 - Even though the path to the file is still listed in the background image filename field.
 - However, the image comes back if you move your mouse over the CDG window, or toggle it on or off

Mac OS 10.13 High Sierra
OpenKJ 1.4.5

**Comment by coyote1357** [comment]
Fixed this a while ago, forgot to close the ticket.
