### ISSUE TITLE
Silence detection not working

### ISSUE THREAD

**Issue by backstagekaraoke** [OpenKJ/OpenKJ#112]
- it is waiting all way to the end of the track, and only then is it starting to bring in the break music
 - I have tested with many tracks just to be sure, and even with tracks that have the last redraw as much as 20 seconds before the track ends, even if audio finishes 10 seconds before track ends, it still waits till the end, then another 2 seconds to fade in break music
 - Abraxa tracks have long post last redraws if you need to test

Mac OS 10.13 High Sierra
OpenKJ 1.4.5

**Comment by coyote1357** [comment]
I'll look into it.  I know it's working with my tracks on Linux as long as the last CDG command has executed, but most of my library is SC, CB, PY, and KV.  But there may be something wrong on macOS.

**Comment by backstagekaraoke** [comment]
@coyote1357 

Tested on:

Mac 10.13.6
OpenKJ 1.5.18

Silence detection is working in the above version.

The only issue is its waiting till there is actual silence rather waiting till the volume goes below a certain threshold and then starts to crossfade in the break music.

It would be great to be able to configure the amount of time before the track ends, that it starts looking for silence or close to silence, and perhaps also a dB threshold that is configurable.

Example:

Start listening/detection 25 seconds before the end of the track, and when the track volume falls below say -60dB, fade the break music in.

A better way is probably, after the last CDG draw, if the volume drops below x amount, fade in the break music.

Tracks with abrupt endings may pose a problem, but they are in the minority, and you can tweak it as you go to get it better and better. For example, you could do something like a look ahead by say 15 seconds, and if the volume happens to increase again after a drop in volume that happens to go below the set threshold, do not fade in the break music until the end of the track.

**Comment by coyote1357** [comment]
Closing this one since the original bug was fixed in a later version.  I'm aware that silence detection could definitely be improved, but that'll have to be a future feature enhancement.
