### ISSUE TITLE
Feature Request: Up now singer screen

### ISSUE THREAD

**Issue by backstagekaraoke** [OpenKJ/OpenKJ#114]
- at the moment, when a song finishes, it just goes back to whatever background image you have set. There is no indication of who is up to sing now.
- the only way to get that is to enable auto play mode

Requested change:

It would be great to have a setting to: 

- display the singer who is up next on the screen in between singers
- specify a background image that is underneath the text overlay

Mac OS 10.13 High Sierra
OpenKJ 1.4.5

**Comment by coyote1357** [comment]
There is already existing code that sort of does this in autoplay mode.  I'll look at making it an option for normal mode.

**Comment by altere987** [comment]
I was going to make a similar suggestion that would display next singer in rotation at the bottom somewhere, or have the next singer highlighted in a different color, but exclude singers with no unsung songs in their list. This would effect the ticker as well. I don't see the need to display singers that haven't put songs up, and calling those people up to "see" if they want to sing is too time consuming.

e.g.: 
Singer 4 - 1 song - [Currently singing]
Singer 1 - 2 songs - 2 songs sung
Singer 2 - 2 songs - 1 song sung
Singer 3 - 5 songs - 2 songs sung

Singer 4 got in after 2 rotations and only put 1 song in. Singer 2 would be listed or highlighted as next, and be next in the ticker. After singer 4 is done, if no one puts anymore songs in, I only have 2 singers, not 4.

**Comment by backstagekaraoke** [comment]
I think the ticker message should simply contain what is actually in the rotation .... so if theres 5 singers in the rotation but only two have songs in their queue, then people should only see 2 singers in the ticker.

Remember patrons don't need to see what the host sees, because if you show the patrons everything, you have no wiggle room to make adjustments.

I do like the idea of having some configurable options for the ticker message like maybe a different font and colour for the next singer. But honestly, its not a big thing, at the end of the day, if singers can see who the next 3 or 4 singers are, in my experience they are fine with that.

**Comment by backstagekaraoke** [comment]
moved to Discussion > Ideas area
