### ISSUE TITLE
Feature Request: Skip singer option

### ISSUE THREAD

**Issue by backstagekaraoke** [OpenKJ/OpenKJ#115]
Mac OS 10.13
OpenKJ 1.4.5

At the moment there is no way to skip a singer from what I can tell. The only way is to remove the singer completely. 

This is a problem when you call up a singer and they are no longer there, or are unavailable at the time. A option to simply skip them and onto the next singer, whilst maintaining the roatation order, would be very useful.

Feature Request:

- a button to skip the singer
- this marks the singer will a specified colour or similar, and moves into the next singer that has songs in their queue

**Comment by coyote1357** [comment]
I'll think on how to do this.  I had just been jumping over them and starting the next singer or dragging them to a different spot in the rotation.

**Comment by backstagekaraoke** [comment]
yeah its actually a really handy feature to have, as it causes less delays in the show.

e.g.

- If a singer has no songs in their queue they get skipped automatically
- If a singer says is disabled/inactive, they get skipped automatically (I've got venues that are split level, so nightclub up top, bar down below. Singers often say "Hey I'm going to have a dance, I'll be back in an hour or two, can you just make me inactive till I return")
- If a singer is called up and they aren't there, a quick option to skip them onto the next singer is great. (I love this feature in Siglos as it immediately updates the 'Up Now' screen, allowing the crowd to see who is now up. I work with some big crowds, and sometimes if singers are up the back, they may not hear their name that well ... having it displayed on all the venue screens is so handy)

**Comment by backstagekaraoke** [comment]
@coyote1357 

I would make this a right click function on the singer if UI real estate will be affected.

**Comment by backstagekaraoke** [comment]
moved to Discussions > Ideas area
