### ISSUE TITLE
Feature Request: Flexible Rotation Management

### ISSUE THREAD

**Issue by backstagekaraoke** [OpenKJ/OpenKJ#117]
Mac OS 10.13
OpenKJ 1.4.5

Linked to #116, it would be great to visually identify the current rotation vs the next rotation. For example, if singer numbers as per #116 were implemented, the rotation could look like this for the first rotation:

CR: #1 - Daniel
CR: #2 - Sally
CR: #3 - Mark
CR: #4 - Louise
CR: #5 - Tim

When you put the first singer in for the next rotation, it could look like:

NR: #6 - Tabitha
CR: #1 - Daniel
CR: #2 - Sally
CR: #3 - Mark
CR: #4 - Louise
CR: #5 - Tim

So with a few more:

NR: #6 - Tabitha
NR: #7 - Nick
NR: #8 - Layla
NR: #9 - Ben
CR: #1 - Daniel
CR: #2 - Sally
CR: #3 - Mark
CR: #4 - Louise
CR: #5 - Tim

Once the current rotation has finished the last singer, it would flip and look like this:

CR: #1 - Tabitha
CR: #2 - Nick
CR: #3 - Layla
CR: #4 - Ben
CR: #5 - Daniel
CR: #6 - Sally
CR: #7 - Mark
CR: #8 - Louise
CR: #9 - Tim

However, that's not exactly fair to the people who came from the start, so a better option would be to space them out, in between each first rotation singer:

CR: #1 - Daniel
CR: #2 - Tabitha
CR: #3 - Sally
CR: #4 - Nick
CR: #5 - Mark
CR: #6 - Layla
CR: #7 - Louise
CR: #9 - Ben
CR: #10 - Tim

Obviously its hard to describe over text, and this is just one suggestion, a lot of the options could be specified as settings, for example:

1. Insert each new singer in between every 'x' singers
 - This would be the setting for when it rolls over to the next rotation, where it puts the 'new' singers

2. Allow each singer to perform 'x' songs per rotation
 - I've heard that some hosts allow two songs back to back per rotation, so this setting could be used for this

Its basically the way I have always done my rotation at shows, I don't use static rotations, so I  go with:

1. Work out your first rotation and decide which singer will be the rotation point for that first rotation
2. Insert new singers in between singers from the previous rotation, trying to it fair. Sometimes I do in between every singer, sometimes I do in between every two singers

**Comment by coyote1357** [comment]
This could be a bit of a nightmare, programmatically, but I'll think on it.

**Comment by backstagekaraoke** [comment]
Yeah it definitely has potential to go wrong if not implemented correctly. Definitely not a right now thing, but something to think about that would separate OKJ from everyone else :)

**Comment by backstagekaraoke** [comment]
moved to Discussions > Ideas area
