### ISSUE TITLE
Feature Request: OpenJ Songbook - Last name initial to separate singers with same name

### ISSUE THREAD

**Issue by backstagekaraoke** [OpenKJ/OpenKJ#118]
Mac OS 10.13
OpenKJ 1.4.5

At the moment with OpenKJ Songbook, when a singer submits a request, they can type anything in the name field. 99% of the time, they will only type in their first name. Unfortunately, this doesn't help when there is 3 John's in the room.

Yes on the incoming requests screen, it has options to 'Add to existing Singer' or 'Create a new singer'. However, this offers no assistance to the host at all, because they have no idea which John submitted that particular song. Introducing a simple thing like the first initial of their last name, eliminates 99% of issues with that, and the only time it would be an issue still, is if you had say 2 'John S' at the show :)

Feature Request

I understand that not every host will agree with this, or want their patrons to do this. So I suggest make it an option for the host to enable or disable in their OpenKJ songbook account settings.

Could just be a tick box for "Require singers to specify their first initial of their last name?".

I have been doing this with my online song request system and it works really well, as pretty much every show I have a number of people with the same name.

**Comment by altere987** [comment]
I've avoided this for the most part by editing the submitreq.php file that now reads:
![screenshot from 2018-12-04 13-55-31](https://user-images.githubusercontent.com/35095431/49469164-6b46ef00-f7cc-11e8-8671-3b9df31310fd.png)

I've since added another warning to the bottom for a select few that liked to change their names during a show, after a few skips they learned to not do that anymore.

**Comment by backstagekaraoke** [comment]
@altere987 where is these submitreq.php and settings.inc files you mentioned? if you're are using the online version of OKJsongbook, how did you edit them on the server side? I'm a bit confused.

**Comment by altere987** [comment]
Sorry, I'm using the Standalone Request Server as it was stated once before the songbook.openkj.org would eventually become a paid service. You can get the StandaloneRequestServer [here](https://github.com/OpenKJ/StandaloneRequestServer). I run it on my local machine with the php server (in Linux using php -S) but there are several you can use such as apache or nginx.

**Comment by altere987** [comment]
@backstagekaraoke that's correct. If a venue provides wifi I'll connect to theirs. If not, I turn my local machine into a hotspot (although this leaves me without the option of connecting to my phone as a hotspot for internet). I was hosting this with our website but ran into a few venues that didn't provide wifi, and cell signal was too bad to get data so there was no internet options at all. As you can tell, there are several options or ways to set this up, it's all in your preference.

**Comment by altere987** [comment]
Since I'm writing this based on something I haven't tried officially on Mac and I don't know what package versions are installed, use this info at your own risk. :)

Download the StandaloneRequestServer and unzip it. I don't use Mac but php may be installed already, if not, `brew install php` should work from a terminal. Don't forget to edit settings.inc. Below is my syntax I use to start it up on port 8000. You can use 'localhost' for the ip but you won't be able to connect from other devices then. I normally make sure of what my local ip is with 'ipconfig' and use that IP address, so that I can connect to it with other devices on the network.

`php -S <ip>:8000 -t <path where you extracted StandaloneRequestServer>`
e.g.: `php -S 192.168.1.103:8000 -t /home/altere987/StandaloneRequestServer`

If everything worked fine, you should get:

> Listening on http://192.163.1.103:8000
Document root is /home/altere987/StandaloneRequestServer
Press Ctrl-C to quit.

There may be some other components you need to install like sqlite and php-sqlite3/php7-sqlite, you should be able to tell if the command displays any errors. Once you verify you can access the site (`http://<ip>:8000`), just change the Server Url under Tools->Network in OpenKJ to: `http://<ip>:8000/api.php`. On Windows, should be pretty straight forward installing php or even apace and possibly sqlite but I've never tried it. Above is the best example I can give as Mac and Linux are somewhat similar in syntax from the terminals.

**Comment by backstagekaraoke** [comment]
@coyote1357 @altere987 ok so yeah Mac already has php installed by default .... I've set it up, and heres what I get when I run it:

Daniels-MBP:~ daniel$ php -S 192.168.8.101:8888 /OKJ/StandAloneRequestServer/api.php
PHP 7.1.16 Development Server started at Thu Dec  6 13:37:25 2018
Listening on http://192.168.8.101:8888
Document root is /Users/daniel
Press Ctrl-C to quit.

So no issues there, it looks to be listening ....

When I try to browse to http://192.168.8.101:8888/api.php .. I get the following error:

Fatal error: Uncaught PDOException: SQLSTATE[HY000] [14] unable to open database file in /OKJ/StandAloneRequestServer/global.inc:3 Stack trace: #0 /OKJ/StandAloneRequestServer/global.inc(3): PDO->__construct('sqlite:/var/www...') #1 /OKJ/StandAloneRequestServer/api.php(2): include_once('/OKJ/StandAlone...') #2 {main} thrown in /OKJ/StandAloneRequestServer/global.inc on line 3

line 3 in global.inc seems to be referencing SQlite:

$db = new PDO("sqlite:$dbFilePath");

I do seem to have SQlite3 installed:

Daniels-MBP:~ daniel$ sqlite3 ?
SQLite version 3.19.3 2017-06-27 16:48:08

I've searched and from what I can tell I also have php-sqlite3 installed:

Daniels-MBP:~ daniel$ mdfind sqlite | grep include
bad path 52C83200-0200-0000-0000-006B00000000
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sqlite3ext.h
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sqlite3.h
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/php/ext/sqlite3/libsqlite/sqlite3.h
/usr/include/apr-1/apu.h
/usr/include/apr-1/apr_dbd.h
/usr/include/module.modulemap
/usr/include/mach/vm_statistics.h
/usr/include/sqlite3ext.h
/usr/include/sqlite3.h
/usr/include/php/main/php_config.h
/usr/include/php/ext/sqlite3/libsqlite/sqlite3.h
/usr/include/php/ext/standard/credits_ext.h
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/php/ext/sqlite3
/usr/include/php/ext/sqlite3
Daniels-MBP:~ daniel$ 

however check brew info, it seems I may be missing some stuff:

Daniels-MBP:~ daniel$ brew info php
php: stable 7.2.12 (bottled)
General-purpose scripting language
https://secure.php.net/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/php.rb
==> Dependencies
Build: httpd ✘, pkg-config ✘
Required: apr ✘, apr-util ✘, argon2 ✘, aspell ✘, autoconf ✘, curl-openssl ✘, freetds ✘, freetype ✘, gettext ✔, glib ✘, gmp ✔, icu4c ✘, jpeg ✘, libpng ✘, libpq ✘, libsodium ✘, libzip ✘, openldap ✘, openssl ✘, pcre ✘, sqlite ✘, tidy-html5 ✘, unixodbc ✘, webp ✘
==> Caveats
To enable PHP in Apache add the following to httpd.conf and restart Apache:
    LoadModule php7_module /usr/local/opt/php/lib/httpd/modules/libphp7.so

    <FilesMatch \.php$>
        SetHandler application/x-httpd-php
    </FilesMatch>

Finally, check DirectoryIndex includes index.php
    DirectoryIndex index.php index.html

The php.ini and php-fpm.ini file can be found in:
    /usr/local/etc/php/7.2/

To have launchd start php now and restart at login:
  brew services start php
Or, if you don't want/need a background service you can just run:
  php-fpm
==> Analytics
install: 45,781 (30 days), 122,352 (90 days), 353,490 (365 days)
install_on_request: 41,541 (30 days), 110,997 (90 days), 318,894 (365 days)
build_error: 0 (30 days)
Daniels-MBP:~ daniel$ 

So I installed php via brew and it looks to be installed:

Daniels-MBP:~ daniel$ brew info php
php: stable 7.2.12 (bottled)
General-purpose scripting language
https://secure.php.net/
/usr/local/Cellar/php/7.2.12_2 (514 files, 75MB) *
  Poured from bottle on 2018-12-06 at 13:55:37
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/php.rb
==> Dependencies
Build: httpd ✘, pkg-config ✘
Required: apr ✔, apr-util ✔, argon2 ✔, aspell ✔, autoconf ✔, curl-openssl ✔, freetds ✔, freetype ✔, gettext ✔, glib ✔, gmp ✔, icu4c ✔, jpeg ✔, libpng ✔, libpq ✔, libsodium ✔, libzip ✔, openldap ✔, openssl ✔, pcre ✔, sqlite ✔, tidy-html5 ✔, unixodbc ✔, webp ✔
==> Caveats
To enable PHP in Apache add the following to httpd.conf and restart Apache:
    LoadModule php7_module /usr/local/opt/php/lib/httpd/modules/libphp7.so

Not sure if I need httpd installed for this to work?

A bit lost now gents, any further guidance would be appreciated :)

**Comment by backstagekaraoke** [comment]
@altere987 yeah I thought that too, but from the info I posted it seems its already installed?

**Comment by altere987** [comment]
SQLite may be installed but it still looks like you're missing pdo_sqlite. 

> Daniels-MBP:~ daniel$ brew info php
php: stable 7.2.12 (bottled)
General-purpose scripting language
https://secure.php.net/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/php.rb
==> Dependencies
Build: httpd ✘, pkg-config ✘
Required: apr ✘, apr-util ✘, argon2 ✘, aspell ✘, autoconf ✘, curl-openssl ✘, freetds ✘, freetype ✘, gettext ✔, glib ✘, gmp ✔, icu4c ✘, jpeg ✘, libpng ✘, libpq ✘, libsodium ✘, libzip ✘, openldap ✘, openssl ✘, pcre ✘, sqlite ✘, tidy-html5 ✘, unixodbc ✘, webp ✘

There's an x next to sqlite. You can try:
`brew install php7-sqlite`
or
`brew install php-sqlite`

Of course you may need to change those to *-sqlite3, I'm not sure on Mac.

**Comment by backstagekaraoke** [comment]
SQLite and SQLite3 are installed (its down a little further in the initial info I included)

I searched homebrew and unfortunately there is not packages for php-SQLite or any variations

**Comment by altere987** [comment]
> Fatal error: Uncaught PDOException: SQLSTATE[HY000] [14] unable to open database file in /OKJ/StandAloneRequestServer/global.inc:3 Stack trace: #0 /OKJ/StandAloneRequestServer/global.inc(3): PDO->__construct('sqlite:/var/www...') #1 /OKJ/StandAloneRequestServer/api.php(2): include_once('/OKJ/StandAlone...') #2 {main} thrown in /OKJ/StandAloneRequestServer/global.inc on line 3

This could be a permissions error, I wasn't paying attention to the path all that close. If you extracted to /OKJ and not your users directory, you need to check that your user has rw permissions to that directory, I'd simply move the directory to your user directory and run from in there. Your dbfilepath in settings.inc should reflect where the standaloneserver is extracted to.

Also, run: `php -m`
If pdo_sqlite isn't listed under [PHP Modules] then you need to get that resolved. If you can't find it in homebrew, you may need to download the php source and compile it in which is where you'd be completely on your own since I don't use Mac.

**Comment by vipermetcaff** [comment]
> Since I'm writing this based on something I haven't tried officially on Mac and I don't know what package versions are installed, use this info at your own risk. :)
> 
> Download the StandaloneRequestServer and unzip it. I don't use Mac but php may be installed already, if not, `brew install php` should work from a terminal. Don't forget to edit settings.inc. Below is my syntax I use to start it up on port 8000. You can use 'localhost' for the ip but you won't be able to connect from other devices then. I normally make sure of what my local ip is with 'ipconfig' and use that IP address, so that I can connect to it with other devices on the network.
> 
> `php -S <ip>:8000 -t <path where you extracted StandaloneRequestServer>`
> e.g.: `php -S 192.168.1.103:8000 -t /home/altere987/StandaloneRequestServer`
> 
> If everything worked fine, you should get:
> 
> > Listening on http://192.163.1.103:8000
> > Document root is /home/altere987/StandaloneRequestServer
> > Press Ctrl-C to quit.
> 
> There may be some other components you need to install like sqlite and php-sqlite3/php7-sqlite, you should be able to tell if the command displays any errors. Once you verify you can access the site (`http://<ip>:8000`), just change the Server Url under Tools->Network in OpenKJ to: `http://<ip>:8000/api.php`. On Windows, should be pretty straight forward installing php or even apace and possibly sqlite but I've never tried it. Above is the best example I can give as Mac and Linux are somewhat similar in syntax from the terminals.
i use xampp on my windows machine i think it will work on mac

> Mac OS 10.13 High Sierra
https://www.apachefriends.org/download.html
i use xampp on my windows machine i think it will work on mac

**Comment by coyote1357** [comment]
The last initial stuff has been added to the hosted (non-standalone) version of the web search/submission app.

Mobile apps will take longer, but are on the roadmap.

**Comment by altere987** [comment]
Will the standalone version be getting any updates?

**Comment by coyote1357** [comment]
Ahh, that should be an easy fix server side, just need to do a trim() on the inputs before concatenating the name and initial to get rid of extraneous whitespace.  I'll look at it tomorrow.

**Comment by backstagekaraoke** [comment]
needs a little bit more work, as people are now just putting dots in the initial box ('.' , '..' etc) which negates the reason for it ....

Can you limit it to only accepting a single letter in the initial box?

Moving forward though, with the upcoming work on the songbook app, and the introduction of a specific kiosk mode, I think it could be made even better by having a realtime sync with the rotation list:

On the Kiosk mode

1. If there is already the same first name in the rotation, the app can prompt the user "There is already someone named 'John' in the rotation, please provide the initial of your last name?"

2. If by some chance (slim chance) they enter the last name initial and its already in the rotation, it can say "There is already someone named 'John B' in the rotation, please go see the host who can enter you in" .... or it could prompt with "There is already someone named 'John B' in the rotation, maybe enter a slightly similar name to differentiate your name?"

Its very slim this will ever happen, but if something can be there just in case thats a bonus :)
