### ISSUE TITLE
No make file found.

### ISSUE THREAD

**Issue by mcarpenterjr** [OpenKJ/OpenKJ#120]
Attempting to build on Ubuntu but there seems to be no make file. After running `/usr/lib/x86_64-linux-gnu/qt5/bin/qmake make` in `OpenKJ/OpenKJ` I get the error `cannot find file: make.` Are there different build instructions?

**Comment by coyote1357** [comment]
You run qmake, then you run make, not qmake make. 

But if you're running a recent version of Ubuntu, there is already a package in the OpenKJ PPA.  

sudo add-apt-repository ppa:openkj/release
sudo apt-get update
sudo apt-get install openkj

**Comment by mcarpenterjr** [comment]
Yea, we're going to attempt to run it off a pi. Excellent looks like I have a couple taglib deps that are missing.
Thanks for the wicked fast response.

**Comment by vaccinemedia** [comment]
@mcarpenterjr did you manage to sort those dependencies and get it running?
