### ISSUE TITLE
Characters outside ASCII range in artist or song name crash the program on play on Windows

### ISSUE THREAD

**Issue by DemianWright** [OpenKJ/OpenKJ#121]
Having characters outside the ASCII range (e.g. ä) in the artist name or song title will immediately crash the program when attempting to play said song. Such files are read into the database and are displayed in the database list correctly.

Tested on 64 bit v1.4.5 stable and 64 bit v1.5.9 unstable on Windows.

**Comment by backstagekaraoke** [comment]
@DemianWright
Happens on Siglos Karaoke Professional as well, I always just use bulk rename utility or a similar tool to change any non-standard characters to their standard equivalent. Never have an issue after that.

Any specific reason you want to keep those characters?

**Comment by DemianWright** [comment]
@backstagekaraoke 
Songs with titles in languages other than English. Converting the characters into the ASCII range is not an option for me as I want to keep the correct titles in their correct format.

**Comment by DemianWright** [comment]
OpenKJ 64 bit v1.5.9 from the Windows unstable downloads: https://openkj.org/windows_unstable_downloads

The characters are displayed in the database list correctly. The only issue I've found so far is attempting to play the file. The issue is not with the file itself as removing the offending characters does allow me to play the file.

**Comment by backstagekaraoke** [comment]
No I meant what other karaoke software are you currently running other than OpenKJ?

Eg. Compuhost, PCDJ Karaoki, Karma, JustKaraoke, KaraFun etc .... and does your current software play these files without issues?

**Comment by DemianWright** [comment]
I'm just starting out so I'm only using OpenKJ. However, I tried the trial version of JustKaraoke 2.0 and it plays these files without issues.

**Comment by coyote1357** [comment]
Just pushed 1.5.13 unstable out for building.  Download and install it and see if it fixes your problems.

**Comment by coyote1357** [comment]
Tentatively closing this and assuming it fixes the issue.  If you try it and it is still failing, please re-open the issue.
