### ISSUE TITLE
Feature Request: OpenKJ Songbook

### ISSUE THREAD

**Issue by backstagekaraoke** [OpenKJ/OpenKJ#122]
On the song request form, it would be really great to have an option for singers to specify if they are singing a duet or as a group.

I have the option on my current online request form that just has “solo - duet - group”

If they select duet an additional field appears asking for the second singers first name. Then when the song comes through to me it has both names and (DUET) next to it.

Eg Daniel M & Sally (DUET)

If they select group, when the song comes through to me it just adds ‘& Friends’ so I know there is gonna be multiple people coming up.

Eg Daniel M & Friends

**Comment by coyote1357** [comment]
Implemented
