### ISSUE TITLE
Bug: OpenKJ 1.5.20 - No Karaoke DB

### ISSUE THREAD

**Issue by backstagekaraoke** [OpenKJ/OpenKJ#126]
MacOS 10.13.6 High Sierra
OpenKJ 1.5.20

Issue
As of 1.5.20, I could no longer play my tracks, karaoke or break music.
I cleared my karaoke db (only had about 100 songs for testing), then re-added about 100 songs back in, however they did not appear in the song list, it remained blank.
I then tried to quit OKJ and the CPU spike to 100% again, it then crashed after a few mins, and the process terminated.
When I opened OKJ again, I got a warning that it was already opened, I clicked OK, and CPU spike to 100% again and crashed after a while
I cleared the plist file, and opened OKJ
I got the same warning about it already being open, I left it on screen for about a minute and OKJ then crashed with the below:

![image](https://user-images.githubusercontent.com/44976193/50147643-6f155e00-0302-11e9-847a-3adfc977d988.png)

here is the crash output

[CrashReport-After Deleting plist again.txt](https://github.com/OpenKJ/OpenKJ/files/2690028/CrashReport-After.Deleting.plist.again.txt)

Heres a video as well:

https://drive.google.com/file/d/1J5I21vDAaAXKe0x6uNGzEflebmqYJ4AJ/view?usp=sharing

**Comment by coyote1357** [comment]
Closing this due to age and because current versions appear to be working okay on my Mac.
