### ISSUE TITLE
openkj unstable 1.5.21

### ISSUE THREAD

**Issue by vipermetcaff** [OpenKJ/OpenKJ#129]
it just randomly crashes when playing karaoke songs

**Comment by vipermetcaff** [comment]
it just randomly crashes when playing karaoke songs

**Comment by backstagekaraoke** [comment]
@vipermetcaff can you please provide more info? 

What OS are you running?

is it happening on every song? or only specific songs?
if its only specific songs, do they have any special characters in the name?
Do you have the output of the logs?
