### ISSUE TITLE
Bug: OpenKJ & Songbook Agent - Emoticons preventing requests from being received

### ISSUE THREAD

**Issue by backstagekaraoke** [OpenKJ/OpenKJ#130]
MacOS & Windows (couldn't test linux)
OpenKJ - 1.x.x - Windows and Mac versions
Songbook Agent - Windows and Mac versions

When a song is submitted and it contains an emoticon, the request is accepted from the singer's perspective, however the request never comes through to OKJ or Songbook Agent

![image](https://user-images.githubusercontent.com/44976193/50623023-a66c4780-0f5d-11e9-8266-61153bd74646.png)

![image](https://user-images.githubusercontent.com/44976193/50623029-b08e4600-0f5d-11e9-8b9a-c3f505463a0c.png)

**Comment by coyote1357** [comment]
Fixed this server side.  It now strips all emoji characters out of any user input.
