### ISSUE TITLE
Feature Request: OpenKJ - CDG+WAV support

### ISSUE THREAD

**Issue by backstagekaraoke** [OpenKJ/OpenKJ#131]
OpenKJ - All Windows and Mac versions
Windows 10
Mac OS 10.13.6 and 10.14

I have just realised that OpenKJ doesn't support WAV files. For all my testing I have just been using a small batch of MP3+G files, so I never noticed. When I went to make the switch to start using OKJ, and import my library, I was confused as to why it wasn't importing 95% of my library.

Could CDG+WAV support please be added?

I don't use MP3 as the dynamic range in them is very poor, even at 320kbps.

**Comment by coyote1357** [comment]
1.5.22 is building now which adds support for non-mp3 audio formats for non-zipped file pairs.

**Comment by backstagekaraoke** [comment]
@coyote1357 ah I see, yeah my files are not zipped, I've actually never zipped my karaoke library, always kept them as separate files.

I have just tested on both Windows and MacOS and WAV files are now being recognized for importing and play successfully. I am not able to test on Linux for you though.

I have also created #132 for the songbook agent
