### ISSUE TITLE
Feature Request : Song Folder column in Search

### ISSUE THREAD

**Issue by jpoconnor61** [OpenKJ/OpenKJ#137]
I don't have SongID populated in my DB, so with multiple results for a Song, I can't tell what Publisher each entry belongs to, unless I preview each line.

I could perhaps do some bulk renaming to populate each filename with something useful in the SongID position and re-import, but it seems the long way round.

If Folder was an available (sortable) column in the main search panel in the Karaoke software, that would make my day. (Obviously the foldername is in the db somewhere).

But if using SongId was to be the only option, access to it when loading or scanning files in from a folder might be helpful - I might set all the songs in one folder with a SongID of 'ZOOM' for example.

JOC

**Comment by backstagekaraoke** [comment]
Use either the media tags naming option or the custom patterns option when adding the folder path to the karaoke import section.
