### ISSUE TITLE
Feature Request: Support mp4 video karaoke files

### ISSUE THREAD

**Issue by drewm27** [OpenKJ/OpenKJ#139]
This is by far the best karaoke player for linux, although the one big feature that holds back part of my collection is that it doesn't support mp4 video karaoke files. It seems like a lot of Chinese karaoke is in this format.

Hopefully it's as easy as linking against ffmpeg or another video decoder to get that feature in.

I may try to work on the code for this feature myself too

**Comment by coyote1357** [comment]
The software already supports mp4 playback...  The video playback is handled via gstreamer.

**Comment by drewm27** [comment]
Strange, it core dumped when I tried to play one. Running Fedora 29 openkj-1.4.5-1.fc29.x86_64

0:00:15.729519147 10220 0x56002e9d3e60 WARN                 basesrc gstbasesrc.c:3583:gst_base_src_start_complete:<source> pad not activated yet
0:00:15.729971072 10220 0x56002e9d3e60 WARN                 basesrc gstbasesrc.c:3583:gst_base_src_start_complete:<source> pad not activated yet
0:00:15.741190295 10220 0x7f7714068800 WARN                 qtdemux qtdemux_types.c:233:qtdemux_type_get: unknown QuickTime node type iods
0:00:15.741224326 10220 0x7f7714068800 WARN                 qtdemux qtdemux_types.c:233:qtdemux_type_get: unknown QuickTime node type gsst
0:00:15.741234720 10220 0x7f7714068800 WARN                 qtdemux qtdemux_types.c:233:qtdemux_type_get: unknown QuickTime node type gstd
0:00:15.741241789 10220 0x7f7714068800 WARN                 qtdemux qtdemux_types.c:233:qtdemux_type_get: unknown QuickTime node type gssd
0:00:15.741248648 10220 0x7f7714068800 WARN                 qtdemux qtdemux_types.c:233:qtdemux_type_get: unknown QuickTime node type gspu
0:00:15.741257037 10220 0x7f7714068800 WARN                 qtdemux qtdemux_types.c:233:qtdemux_type_get: unknown QuickTime node type gspm
0:00:15.741264089 10220 0x7f7714068800 WARN                 qtdemux qtdemux_types.c:233:qtdemux_type_get: unknown QuickTime node type gshh
0:00:15.741294235 10220 0x7f7714068800 WARN                 qtdemux qtdemux.c:3031:qtdemux_parse_trex:<qtdemux0> failed to find fragment defaults for stream 1
0:00:15.741354378 10220 0x7f7714068800 WARN                 qtdemux qtdemux.c:3031:qtdemux_parse_trex:<qtdemux0> failed to find fragment defaults for stream 2
0:00:15.741448182 10220 0x7f7714068800 WARN                 basesrc gstbasesrc.c:2445:gst_base_src_update_length:<source> processing at or past EOS
0:00:15.746876451 10220 0x7f7714068800 WARN            uridecodebin gsturidecodebin.c:921:unknown_type_cb:<uridecodebin0> warning: No decoder available for type 'audio/mpeg, mpegversion=(int)4, framed=(boolean)true, stream-format=(string)raw, level=(string)2, base-profile=(string)lc, profile=(string)lc, codec_data=(buffer)1210, rate=(int)44100, channels=(int)2'.
0:00:15.753880518 10220 0x7f7714068800 WARN            uridecodebin gsturidecodebin.c:921:unknown_type_cb:<uridecodebin0> warning: No decoder available for type 'video/x-h264, stream-format=(string)avc, alignment=(string)au, level=(string)1.1, profile=(string)baseline, codec_data=(buffer)0142000bfde1000f6742000bbb40b047f360203c2010a801000568ce0a5c80, width=(int)352, height=(int)262, framerate=(fraction)30000/1001, pixel-aspect-ratio=(fraction)1/1, interlace-mode=(string)progressive, chroma-format=(string)4:2:0, bit-depth-luma=(uint)8, bit-depth-chroma=(uint)8, parsed=(boolean)true'.
0:00:15.753997658 10220 0x7f7714068800 WARN               decodebin gstdecodebin2.c:4640:gst_decode_bin_expose:<decodebin0> error: no suitable plugins found:
Missing decoder: H.264 (Baseline Profile) (video/x-h264, stream-format=(string)avc, alignment=(string)au, level=(string)1.1, profile=(string)baseline, codec_data=(buffer)0142000bfde1000f6742000bbb40b047f360203c2010a801000568ce0a5c80, width=(int)352, height=(int)262, framerate=(fraction)30000/1001, pixel-aspect-ratio=(fraction)1/1, interlace-mode=(string)progressive, chroma-format=(string)4:2:0, bit-depth-luma=(uint)8, bit-depth-chroma=(uint)8, parsed=(boolean)true)
Missing decoder: MPEG-4 AAC (audio/mpeg, mpegversion=(int)4, framed=(boolean)true, stream-format=(string)raw, level=(string)2, base-profile=(string)lc, profile=(string)lc, codec_data=(buffer)1210, rate=(int)44100, channels=(int)2)

0:00:15.754038472 10220 0x7f7714068800 WARN            uridecodebin gsturidecodebin.c:988:no_more_pads_full:<uridecodebin0> error: no suitable plugins found:
gstdecodebin2.c(4640): gst_decode_bin_expose (): /GstPlayBin:playBin/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin0:
no suitable plugins found:
Missing decoder: H.264 (Baseline Profile) (video/x-h264, stream-format=(string)avc, alignment=(string)au, level=(string)1.1, profile=(string)baseline, codec_data=(buffer)0142000bfde1000f6742000bbb40b047f360203c2010a801000568ce0a5c80, width=(int)352, height=(int)262, framerate=(fraction)30000/1001, pixel-aspect-ratio=(fraction)1/1, interlace-mode=(string)progressive, chroma-format=(string)4:2:0, bit-depth-luma=(uint)8, bit-depth-chroma=(uint)8, parsed=(boolean)true)
Missing decoder: MPEG-4 AAC (audio/mpeg, mpegversion=(int)4, framed=(boolean)true, stream-format=(string)raw, level=(string)2, base-profile=(string)lc, profile=(string)lc, codec_data=(buffer)1210, rate=(int)44100, channels=(int)2)

0:00:15.754518317 10220 0x7f7714068800 WARN                 qtdemux qtdemux.c:6073:gst_qtdemux_loop:<qtdemux0> error: Internal data stream error.
0:00:15.754532750 10220 0x7f7714068800 WARN                 qtdemux qtdemux.c:6073:gst_qtdemux_loop:<qtdemux0> error: streaming stopped, reason not-linked (-1)
KAudio entered UnknownState
"KA"  - Gst msg type:  8192  Gst msg name:  stream-status
"KA"  - Gst msg type:  8192  Gst msg name:  stream-status
"KA"  - Gst msg type:  8192  Gst msg name:  stream-status
"KA"  - Gst msg type:  8192  Gst msg name:  stream-status
"KA"  - Gst msg type:  8192  Gst msg name:  stream-status
"KA"  - Gst msg type:  8192  Gst msg name:  stream-status
"KA"  - Gst warning:  No decoder available for type 'audio/mpeg, mpegversion=(int)4, framed=(boolean)true, stream-format=(string)raw, level=(string)2, base-profile=(string)lc, profile=(string)lc, codec_data=(buffer)1210, rate=(int)44100, channels=(int)2'.
"KA"  - Gst debug:  gsturidecodebin.c(921): unknown_type_cb (): /GstPlayBin:playBin/GstURIDecodeBin:uridecodebin0
free(): invalid pointer
Aborted (core dumped)

**Comment by coyote1357** [comment]
You're missing mp4 support in your gstreamer plugins.  I think it's part of the gstreamer1-plugins-bad package.  If not, it may be in one of the rpmfusion gstreamer1 plugin packages.

**Comment by coyote1357** [comment]
Yeah, that. LOL Sorry, didn't see your last comment until after I had typed my last response.  Glad you got it working! :)
