### ISSUE TITLE
OpenKJ 1.4.7 suddenly not adding Karaoke DBs

### ISSUE THREAD

**Issue by GrafXMan** [OpenKJ/OpenKJ#141]

**Comment by coyote1357** [comment]
So, you're doing a db update and it's not adding the new songs to your database?  Also, what OS are you running on?

**Comment by GrafXMan** [comment]
I am attempting to add a location to the list of places to look. It
shows the details dialog and that had no problems. Then you click ok
and nothing is added to the list.
And I am on Linux :-)

**Comment by jpoconnor61** [comment]
I'm seeing this too, with both recently released stable Song Agent and previous version (Win64), although the problem  might be at the other end.

I have tried a few updates from the Agent and a number of new songs in my csv data are being parsed correctly by the agent, (visible in the listing), the Update Songbook seems to work ok with no errors, but the new songs cannot be found in webpage or app.

JOC

**Comment by coyote1357** [comment]
I have been unable to duplicate the original bug (which I interpreted to be the local DB, not songbook) and none of my testers have either.  I'm going to close this, but if it's still an issue, please feel free to re-open the issue and we'll look further.

@jpoconnor61 - If you're still experiencing the problem you described with the Songbook Agent, please open an issue over here: https://github.com/OpenKJ/SongbookAgent
