### ISSUE TITLE
Feature Request: Version preference/weighting option for songs

### ISSUE THREAD

**Issue by backstagekaraoke** [OpenKJ/OpenKJ#142]
It would be really great to have the ability to set a preference for which version of a song is used/displayed first globally, and also per track, utilizing prefixes of the track names. 

Example of global preference: 

1. Lets say you have 4 versions of 'Red Hot Chili Peppers - Under the Bridge', one by Sunfly, SoundChoice, Legends and Zoom. 

2. In your particular library, you feel that Legends versions of tracks are the best for what you need. 

3. You have an option to enter the prefixes for your Legends tracks and give them a preference of '1'. e.g. Any track with a prefix of 'LG' will have a preference of '1'. 

4. You can then set a preference order for your other versions - e.g. Prefixes for Sunfly - SF, SFMW, SFG etc get '2' .... prefixes for SoundChoice - SC, SCH etc get '3' and so on.

5. This would also apply to the OKJ songbook platform, for when it sends songs through, it selects the correct file based on the above preferences.

Example of per track 

1. Keeping with the model above, there will be instances where, whilst you have specified a particular manufacturer as the first preference, you know that a specific track from a lower preference manufacture is much better, and wish to override the global setting. 

2. So in each song, you will have an option to override the global preference setting and make that track the default. e.g. "Override global preference setting for this track - This means when this song is selected, Siglos will use this track, regardless of the global preference setting" 

So over time, you will be able to identify the best tracks to use for each song.

I think it would be a very useful feature, and just another thing to 'help' the host save seconds here and seconds there.

**Comment by oasiz** [comment]
This is an excellent suggestion, good shout!

I tend to opt for the Mr Entertainer version, then Zoom/Sunfly etc and would love to see them ordered that way to save time (and to make it easier if/when someone with less experience is adding a song)

**Comment by backstagekaraoke** [comment]
@oasiz yep, basically anything that saves a few seconds here and there will help, and adds up over time 👍

**Comment by backstagekaraoke** [comment]
moved to new Discussions > Ideas area
