### ISSUE TITLE
Bug: OpenKJ - Autoplay mode doesn't work if background image is set

### ISSUE THREAD

**Issue by backstagekaraoke** [OpenKJ/OpenKJ#147]
OpenKJ 1.5.33
Windows 10 64bit

Bug: If a background image is set, even if you enable Karaoke Autoplay mode, it doesn't engage the autoplay, until you clear the background image setting.

Steps I took:

1. Set background image
2. Tested background image worked - Yes
3. Left background image enabled
4. Enabled Karaoke Autoplay mode
5. Played a song, at the end autoplay didn't kick in, just the background image sat there.
6. Tried 5 songs to be sure
7. Cleared the background image
8. Tested again - Autoplay mode kicked in at the end of song

Suggestion 1 - If a background image is set the karaoke autoplay mode text should overlay on top of the background image.

Suggestion 2 - If overlay on top of the background image is not possible, override the background image automatically if autoplay mode is enabled.

**Comment by coyote1357** [comment]
Can you verify that this is still a problem?  I've been unable to duplicate it in the current version.

**Comment by coyote1357** [comment]
I'm assuming this is fixed, if it's still a problem, feel free to re-open the issue or just let me know.
