### ISSUE TITLE
Feature Request: OpenKJ - Break Music Fade in override

### ISSUE THREAD

**Issue by backstagekaraoke** [OpenKJ/OpenKJ#150]
OpenKJ
All versions

At the moment with ‘Silence Detection’ it seems to still wait until after the last CDG draw before fading the break music in.

However some tracks sometimes have quite a long silence after the last CDG draw, which causes dead air. I’ve seen as long as 10 seconds.

My suggestion is to be able to:

1. Option to override normal silence detection - in case some hosts wish to stick with the default option

2. Option to specify a volume threshold of when the fade in will start. Eg - once volume drops below -50dB start fade in

3. Option to specify the amount of time you wish the fade in to take until it reaches the pre set break music volume level - Eg take 2.5 seconds to fade up to break music level

4. Option to specify the amount of seconds prior to the end of the track that OKJ starts listening for a drop below the volume threshold - Eg start listening 10 seconds prior to end.

**Comment by coyote1357** [comment]
Good ideas. Though, due to the way the fader works (dependent on current volume level), giving a set time would be hard.  Would be possible to set a fade speed though.  I also wonder if I can improve the CDG draw based safety measure to accurately tell when the lyrics are likely done drawing/swiping vs when the actual last draw is.  I'll have to mull that over.

**Comment by backstagekaraoke** [comment]
@coyote1357 

A much easier way is simply not worry about trying to reset the volume each time a new file is loaded, do it like a DJ with two decks .... one deck for break music, one deck for for karaoke and just simple organic cross-fading between them .... and just have some options that the user can use for customising the crossfade - e.g. when fading from Deck A to Deck B take 3 seconds etc

So for example lets say you have:

Deck B - Break music - 50% volume
Deck K - Karaoke Music - 100% volume

On each deck you can set its own maximum volume limit - this is simply the volume it ends up being once a full fade is completed.

Deck B is playing playing break music at its set volume
Karaoke track is started in Deck K
Cross-fade starts from Deck B to Deck K based on the user specified parameters until it reaches it set max volume  
Deck K is now audible
Karaoke song is nearing the end
Cross-fade starts from Deck K to Deck B based on the user specified parameters until it reaches it set max volume
Deck B is now audible

So essentially its simply acting like a volume control for which deck you want to be audible. The only issue you MIGHT run into is when the cross-fade goes back to Deck B, if the track is ending, you may not hear anything for a second or two until the next song starts playing.

You could address this either adding two decks in for break music - say Deck B1 and Deck B2, and simply have it cross-fade between those two decks, so there is never any silence with the break music. When a track on Deck K is started, the main cross-fade fades over to Deck K. The break music continues to play all the time (unless explicitly stopped by host), but its simply not audible when Deck K takes the fade priority.

Honestly, you are just mimicking the same as you would with faders on a mixer, and this would probably eliminate the issues of when it has to 'load' each break track and reference the volume again.

**Comment by backstagekaraoke** [comment]
this is being handled in a different feature addition anyway
