### ISSUE TITLE
Feature Request: OpenKJ - Song Countdown Timer

### ISSUE THREAD

**Issue by backstagekaraoke** [OpenKJ/OpenKJ#153]
OpenKJ - All Versions
Linux, Mac, Windows

One awesome feature Siglos has is a countdown timer that shows you how long until the end of a song. This allows singers to see if they can run to the toilet or sneak out for a smoke or something. 

The options are simple:

1. Enable or Disable countdown timer

2. Display on the left or right of the ticker message, and it uses the same display height as the ticker message.

3. You can set the thresholds for the remaining time, which changes the countdown background colour.

e.g. 
Less than 3 mins remaining = Green background
Less than 2 mins remaining = Yellow background
Less than 1 min remaining = Red background

**Comment by coyote1357** [comment]
Had to implement it differently due to limitations in layout options for the ticker, so it sits above the ticker on the bottom right of the screen.  Has its own font and color settings, but no traffic light colors, may add that later.

Available as of version 1.5.40 unstable

**Comment by backstagekaraoke** [comment]
@coyote1357 as discussed previously (sent you videos), the countdown timer only works when the ticker message is enabled. There is hosts who may not want to use the ticker message but want the countdown timer.

Also you can only edit the ticker message when its enabled, so the audience can see as you type. It would be better to be able to type your update and then have a Update Ticker button to commit the changes.

**Comment by coyote1357** [comment]
That's really odd... It works fine without the ticker on my system...

**Comment by backstagekaraoke** [comment]
As per the videos I sent, countdown still not working without the ticker message being enabled. Flickers on and off. Doesn't matter what size the countdown font is set to.

Only seems to happen in fullscreen mode, Windowed mode displays correctly, but windowed mode is not desirable.

**Comment by backstagekaraoke** [comment]
I will also try on a different TV to rule out a specific TV issue

**Comment by backstagekaraoke** [comment]
@coyote1357
Tried on 3 different TVs and the same issue happens on all of them

**Comment by backstagekaraoke** [comment]
Looks to be fixed now mate - up to you if you want to add in the options to specify the different colours for different time thresholds - but if not, good to close off :)
