### ISSUE TITLE
Feature Request: OpenKJ - Undock and Float Request Window

### ISSUE THREAD

**Issue by backstagekaraoke** [OpenKJ/OpenKJ#154]
OpenKJ - All Versions
Linux, Mac, Windows

At the moment, its a bit of a pain if you are in the middle of adding songs from the request window, and you need to do something else, that you have to close the request window.

It would be good to have the option to undock the request window and have it as a floating window.

**Comment by altere987** [comment]
I haven't been this busy before, but I second this request as I see the usefulness, as long as auto floats to the primary display.

**Comment by coyote1357** [comment]
I'll remove the modality flag on the window, that way it will be treated independently from the main window and won't block interactions with it.

**Comment by backstagekaraoke** [comment]
@coyote1357 ok mate, look forward to testing it out :)

**Comment by coyote1357** [comment]
Changes are in 1.5.51 unstable

**Comment by backstagekaraoke** [comment]
@coyote1357 tested and working for me.
