### ISSUE TITLE
https not secure on openkj.org

### ISSUE THREAD

**Issue by vipermetcaff** [OpenKJ/OpenKJ#162]
![image](https://user-images.githubusercontent.com/6171564/55530243-8df5f100-5662-11e9-9bca-53373fe9b68b.png)

**Comment by altere987** [comment]
Yes, we haven't heard from our trusty OpenKJ coder in a little over a month, hope everything is alright. Looking forward to some updates.

**Comment by coyote1357** [comment]
Should be fixed, the script that updates the ssl certs automatically apparently isn't running as it should.

Sorry I've been MIA lately.  Dealing with some family medical stuff.
