### ISSUE TITLE
Bug: OpenKJ - Ticker showing empty singers as "None"

### ISSUE THREAD

**Issue by backstagekaraoke** [OpenKJ/OpenKJ#165]
Linux Mint 19
Kernels 4.15.47 & 5.0.*
OpenKJ 1.5.*

Bug:

I have my ticker message set to not show Rotation Info, and custom message is just:

"Up now is %curSinger%         |      Get ready %nextSinger% you are up next!        |"

However the ticker message is showing singers that have no songs in their queue .... so it shows "None" on the ticker for all of those.

**Comment by backstagekaraoke** [comment]
FYI this could possibly tie into #157 and knock over two things at once.

Just a thought.

**Comment by coyote1357** [comment]
Actually, the %curSinger% and %nextSinger% don't take into account whether a singer has a song in or not, nothing in the ticker does as of yet, so if you have singers in rotation, they should never show as "none".  I'll have to figure out what's going on here.

**Comment by coyote1357** [comment]
Okay, ticker still doesn't change based on whether a singer has songs in their queue or not, but I did find the problem that was making cur singer show up as "none".  It was doing this because it was basing it on the on screen label under the media controls that shows who's singing the currently playing song rather than using the actual rotation data.  If a song wasn't currently playing, it would always show "none" in the ticker.

**Comment by backstagekaraoke** [comment]
1.5.64 has kind of fixed the issue of %curSinger showing up as none, however this doesn't apply when the rotation hasn't started yet.

Steps to replicate

- Enable ticker
- In message box put "Up Now: %curSinger | Up Next: %nextSinger"
- Then add two singers "Singer 1 and Singer 2" into the rotation without any songs
- You will see in the rotation that Singer 2 has position '1' next to their name - I know why, but its a bit confusing, they should really have position '2' as they are second not first.
- The ticker message displays nothing for Singer 1, and 'Up Next: Singer 2'
- Enter some songs for both singers
- When you double click Singer 1 to start, Singer 2 position now changes to '2'

**Comment by coyote1357** [comment]
I get what you're getting at.  Now, if nobody is a current singer, it will select the singer at the top of the rotation as the current singer displayed.

Also renamed the Pos column to Wait, as that is what it was actually intended to denote.
