### ISSUE TITLE
Bug: OpenKJ - Break Music Volume Increase on each manual track load

### ISSUE THREAD

**Issue by backstagekaraoke** [OpenKJ/OpenKJ#167]
OpenKJ
Linux
All versions

Issue:

When manually loading up a break music track, the volume increases in increments on each track you load. This only happens when manually loading the tracks.

Debug Log

INFO: "BM"  - AudioBackendGstreamer::stop( false ) called ()
INFO: "BM"  - AudioBackendGstreamer::stop -- Fading enabled.  Fading out audio volume ()
INFO: fadeOut(  true  ) called ()
INFO: "BM"  - Fader started ()
INFO: Timer fader - Current:  0.48  Target:  0 ()
INFO: "BM"  - emitting volume changed:  43 ()
INFO: Timer fader - Current:  0.43  Target:  0 ()
INFO: "BM"  - emitting volume changed:  37 ()
INFO: Timer fader - Current:  0.38  Target:  0 ()
INFO: "BM"  - emitting volume changed:  33 ()
INFO: Timer fader - Current:  0.33  Target:  0 ()
INFO: "BM"  - emitting volume changed:  27 ()
INFO: Timer fader - Current:  0.28  Target:  0 ()
INFO: "BM"  - emitting volume changed:  22 ()
INFO: Timer fader - Current:  0.23  Target:  0 ()
INFO: "BM"  - emitting volume changed:  17 ()
INFO: Timer fader - Current:  0.18  Target:  0 ()
INFO: "BM"  - emitting volume changed:  12 ()
INFO: Timer fader - Current:  0.13  Target:  0 ()
INFO: "BM"  - emitting volume changed:  7 ()
INFO: Timer fader - Current:  0.08  Target:  0 ()
INFO: "BM"  - emitting volume changed:  2 ()
INFO: Timer fader - Current:  0.03  Target:  0 ()
INFO: "BM"  - fader finished ()
INFO: fadeOut returned ()
INFO: "BM"  - AudioBackendGstreamer::stop -- Fading complete ()
INFO: "BM"  - AudioBackendGstreamer::stop -- Stoping playback ()
INFO: DlgCdg::setShowBgImage( true ) called ()
INFO: triggerBg called ()
INFO: DlgCdg::setShowBgImage( true ) called ()
INFO: "BM"  - AudioBackendGstreamer::stop -- Setting volume back to original setting:  48 ()
INFO: "BM"  - setVolume - setting to linear:  0.110592 ()
INFO: AudioFader set paused state to:  true ()
INFO: "BM"  - Initializing gst
 ()
INFO: "BM"  - setVolume - setting to linear:  0.110592 ()
INFO: AudioFader set paused state to:  false ()
INFO: "BM"  - Setting output device to device idx:  0 ()
INFO: "BM"  - Default device selected ()
INFO: "BM"  - Linking deinterleave pad src_0 to queueSinkPadL ()
INFO: "BM"  - link succeeded ()
INFO: "BM"  - Linking complete ()
INFO: "BM"  - Linking deinterleave pad src_1 to queueSinkPadR ()
INFO: "BM"  - link succeeded ()
INFO: "BM"  - Linking complete ()
INFO: "BM"  - emitting volume changed:  78 ()
INFO: "BM"  - Gst msg type:  262144  Gst msg name:  duration-changed ()
INFO: "BM"  - Gst msg type:  268435456  Gst msg name:  stream-start ()
INFO: "BM"  - Gst msg type:  524288  Gst msg name:  latency ()
INFO: "BM"  - Gst msg type:  2097152  Gst msg name:  async-done ()
INFO: "BM"  - Gst msg type:  2048  Gst msg name:  new-clock ()
INFO: "BM"  - AudioBackendGstreamer::stop( false ) called ()
INFO: "BM"  - AudioBackendGstreamer::stop -- Fading enabled.  Fading out audio volume ()
INFO: fadeOut(  true  ) called ()
INFO: "BM"  - Fader started ()
INFO: Timer fader - Current:  0.782974  Target:  0 ()
INFO: "BM"  - emitting volume changed:  73 ()
INFO: Timer fader - Current:  0.732974  Target:  0 ()
INFO: "BM"  - emitting volume changed:  68 ()
INFO: Timer fader - Current:  0.682974  Target:  0 ()
INFO: "BM"  - emitting volume changed:  63 ()
INFO: Timer fader - Current:  0.632974  Target:  0 ()
INFO: "BM"  - emitting volume changed:  58 ()
INFO: Timer fader - Current:  0.582974  Target:  0 ()
INFO: "BM"  - emitting volume changed:  53 ()
INFO: Timer fader - Current:  0.532974  Target:  0 ()
INFO: "BM"  - emitting volume changed:  48 ()
INFO: Timer fader - Current:  0.482974  Target:  0 ()
INFO: "BM"  - emitting volume changed:  43 ()
INFO: Timer fader - Current:  0.432974  Target:  0 ()
INFO: "BM"  - emitting volume changed:  38 ()
INFO: Timer fader - Current:  0.382974  Target:  0 ()
INFO: "BM"  - emitting volume changed:  33 ()
INFO: Timer fader - Current:  0.332974  Target:  0 ()
INFO: "BM"  - emitting volume changed:  28 ()
INFO: Timer fader - Current:  0.282974  Target:  0 ()
INFO: "BM"  - emitting volume changed:  23 ()
INFO: Timer fader - Current:  0.232974  Target:  0 ()
INFO: "BM"  - emitting volume changed:  18 ()
INFO: Timer fader - Current:  0.182974  Target:  0 ()
INFO: "BM"  - emitting volume changed:  13 ()
INFO: Timer fader - Current:  0.132974  Target:  0 ()
INFO: "BM"  - emitting volume changed:  8 ()
INFO: Timer fader - Current:  0.0829735  Target:  0 ()
INFO: "BM"  - emitting volume changed:  3 ()
INFO: Timer fader - Current:  0.0329735  Target:  0 ()
INFO: "BM"  - fader finished ()
INFO: fadeOut returned ()
INFO: "BM"  - AudioBackendGstreamer::stop -- Fading complete ()
INFO: "BM"  - AudioBackendGstreamer::stop -- Stoping playback ()
INFO: DlgCdg::setShowBgImage( true ) called ()
INFO: triggerBg called ()
INFO: DlgCdg::setShowBgImage( true ) called ()
INFO: "BM"  - AudioBackendGstreamer::stop -- Setting volume back to original setting:  78 ()
INFO: "BM"  - setVolume - setting to linear:  0.474552 ()
INFO: AudioFader set paused state to:  true ()
INFO: "BM"  - Initializing gst
 ()
INFO: "BM"  - setVolume - setting to linear:  0.474552 ()
INFO: AudioFader set paused state to:  false ()
INFO: "BM"  - Setting output device to device idx:  0 ()
INFO: "BM"  - Default device selected ()
INFO: "BM"  - Linking deinterleave pad src_0 to queueSinkPadL ()
INFO: "BM"  - link succeeded ()
INFO: "BM"  - Linking complete ()
INFO: "BM"  - Linking deinterleave pad src_1 to queueSinkPadR ()
INFO: "BM"  - link succeeded ()
INFO: "BM"  - Linking complete ()
INFO: "BM"  - emitting volume changed:  92 ()
INFO: "BM"  - Gst msg type:  262144  Gst msg name:  duration-changed ()
INFO: "BM"  - Gst msg type:  268435456  Gst msg name:  stream-start ()
INFO: "BM"  - Gst msg type:  524288  Gst msg name:  latency ()
INFO: "BM"  - Gst msg type:  2097152  Gst msg name:  async-done ()
INFO: "BM"  - Gst msg type:  2048  Gst msg name:  new-clock ()
INFO: "BM"  - AudioBackendGstreamer::stop( false ) called ()
INFO: "BM"  - AudioBackendGstreamer::stop -- Fading enabled.  Fading out audio volume ()
INFO: fadeOut(  true  ) called ()
INFO: "BM"  - Fader started ()
INFO: Timer fader - Current:  0.920516  Target:  0 ()
INFO: "BM"  - emitting volume changed:  87 ()
INFO: Timer fader - Current:  0.870516  Target:  0 ()
INFO: "BM"  - emitting volume changed:  82 ()
INFO: Timer fader - Current:  0.820516  Target:  0 ()
INFO: "BM"  - emitting volume changed:  77 ()
INFO: Timer fader - Current:  0.770516  Target:  0 ()
INFO: "BM"  - emitting volume changed:  72 ()
INFO: Timer fader - Current:  0.720516  Target:  0 ()
INFO: "BM"  - emitting volume changed:  67 ()
INFO: Timer fader - Current:  0.670516  Target:  0 ()
INFO: "BM"  - emitting volume changed:  62 ()
INFO: Timer fader - Current:  0.620516  Target:  0 ()
INFO: "BM"  - emitting volume changed:  57 ()
INFO: Timer fader - Current:  0.570516  Target:  0 ()
INFO: "BM"  - emitting volume changed:  52 ()
INFO: Timer fader - Current:  0.520516  Target:  0 ()
INFO: "BM"  - emitting volume changed:  47 ()
INFO: Timer fader - Current:  0.470516  Target:  0 ()
INFO: "BM"  - emitting volume changed:  42 ()
INFO: Timer fader - Current:  0.420516  Target:  0 ()
INFO: "BM"  - emitting volume changed:  37 ()
INFO: Timer fader - Current:  0.370516  Target:  0 ()
INFO: "BM"  - emitting volume changed:  32 ()
INFO: Timer fader - Current:  0.320516  Target:  0 ()
INFO: "BM"  - emitting volume changed:  27 ()
INFO: Timer fader - Current:  0.270516  Target:  0 ()
INFO: "BM"  - emitting volume changed:  22 ()
INFO: Timer fader - Current:  0.220516  Target:  0 ()
INFO: "BM"  - emitting volume changed:  17 ()
INFO: Timer fader - Current:  0.170516  Target:  0 ()
INFO: "BM"  - emitting volume changed:  12 ()
INFO: Timer fader - Current:  0.120516  Target:  0 ()
INFO: "BM"  - emitting volume changed:  7 ()
INFO: Timer fader - Current:  0.0705164  Target:  0 ()
INFO: "BM"  - emitting volume changed:  2 ()
INFO: Timer fader - Current:  0.0205164  Target:  0 ()
INFO: "BM"  - fader finished ()
INFO: fadeOut returned ()
INFO: "BM"  - AudioBackendGstreamer::stop -- Fading complete ()
INFO: "BM"  - AudioBackendGstreamer::stop -- Stoping playback ()
INFO: DlgCdg::setShowBgImage( true ) called ()
INFO: triggerBg called ()
INFO: DlgCdg::setShowBgImage( true ) called ()
INFO: "BM"  - AudioBackendGstreamer::stop -- Setting volume back to original setting:  92 ()
INFO: "BM"  - setVolume - setting to linear:  0.778688 ()
INFO: AudioFader set paused state to:  true ()
INFO: "BM"  - Initializing gst
 ()
INFO: "BM"  - setVolume - setting to linear:  0.778688 ()
INFO: AudioFader set paused state to:  false ()
INFO: "BM"  - Setting output device to device idx:  0 ()
INFO: "BM"  - Default device selected ()
INFO: "BM"  - Linking deinterleave pad src_0 to queueSinkPadL ()
INFO: "BM"  - link succeeded ()
INFO: "BM"  - Linking complete ()
INFO: "BM"  - Linking deinterleave pad src_1 to queueSinkPadR ()
INFO: "BM"  - link succeeded ()
INFO: "BM"  - Linking complete ()
INFO: "BM"  - emitting volume changed:  97 ()
INFO: "BM"  - Gst msg type:  262144  Gst msg name:  duration-changed ()
INFO: "BM"  - Gst msg type:  268435456  Gst msg name:  stream-start ()
INFO: "BM"  - Gst msg type:  524288  Gst msg name:  latency ()
INFO: "BM"  - Gst msg type:  2097152  Gst msg name:  async-done ()
INFO: "BM"  - Gst msg type:  2048  Gst msg name:  new-clock ()
INFO: "BM"  - AudioBackendGstreamer::stop( false ) called ()
INFO: "BM"  - AudioBackendGstreamer::stop -- Fading enabled.  Fading out audio volume ()
INFO: fadeOut(  true  ) called ()
INFO: "BM"  - Fader started ()
INFO: Timer fader - Current:  0.972589  Target:  0 ()
INFO: "BM"  - emitting volume changed:  92 ()
INFO: Timer fader - Current:  0.922589  Target:  0 ()
INFO: "BM"  - emitting volume changed:  87 ()
INFO: Timer fader - Current:  0.872589  Target:  0 ()
INFO: "BM"  - emitting volume changed:  82 ()
INFO: Timer fader - Current:  0.822589  Target:  0 ()
INFO: "BM"  - emitting volume changed:  77 ()
INFO: Timer fader - Current:  0.772589  Target:  0 ()
INFO: "BM"  - emitting volume changed:  72 ()
INFO: Timer fader - Current:  0.722589  Target:  0 ()
INFO: "BM"  - emitting volume changed:  67 ()
INFO: Timer fader - Current:  0.672589  Target:  0 ()
INFO: "BM"  - emitting volume changed:  62 ()
INFO: Timer fader - Current:  0.622589  Target:  0 ()
INFO: "BM"  - emitting volume changed:  57 ()
INFO: Timer fader - Current:  0.572589  Target:  0 ()
INFO: "BM"  - emitting volume changed:  52 ()
INFO: Timer fader - Current:  0.522589  Target:  0 ()
INFO: "BM"  - emitting volume changed:  47 ()
INFO: Timer fader - Current:  0.472589  Target:  0 ()
INFO: "BM"  - emitting volume changed:  42 ()
INFO: Timer fader - Current:  0.422589  Target:  0 ()
INFO: "BM"  - emitting volume changed:  37 ()
INFO: Timer fader - Current:  0.372589  Target:  0 ()
INFO: "BM"  - emitting volume changed:  32 ()
INFO: Timer fader - Current:  0.322589  Target:  0 ()
INFO: "BM"  - emitting volume changed:  27 ()
INFO: Timer fader - Current:  0.272589  Target:  0 ()
INFO: "BM"  - emitting volume changed:  22 ()
INFO: Timer fader - Current:  0.222589  Target:  0 ()
INFO: "BM"  - emitting volume changed:  17 ()
INFO: Timer fader - Current:  0.172589  Target:  0 ()
INFO: "BM"  - emitting volume changed:  12 ()
INFO: Timer fader - Current:  0.122589  Target:  0 ()
INFO: "BM"  - emitting volume changed:  7 ()
INFO: Timer fader - Current:  0.0725888  Target:  0 ()
INFO: "BM"  - emitting volume changed:  2 ()
INFO: Timer fader - Current:  0.0225888  Target:  0 ()
INFO: "BM"  - fader finished ()
INFO: fadeOut returned ()
INFO: "BM"  - AudioBackendGstreamer::stop -- Fading complete ()
INFO: "BM"  - AudioBackendGstreamer::stop -- Stoping playback ()
INFO: DlgCdg::setShowBgImage( true ) called ()
INFO: triggerBg called ()
INFO: DlgCdg::setShowBgImage( true ) called ()
INFO: "BM"  - AudioBackendGstreamer::stop -- Setting volume back to original setting:  97 ()
INFO: "BM"  - setVolume - setting to linear:  0.912673 ()
INFO: AudioFader set paused state to:  true ()
INFO: "BM"  - Initializing gst
 ()
INFO: "BM"  - setVolume - setting to linear:  0.912673 ()
INFO: AudioFader set paused state to:  false ()
INFO: "BM"  - Setting output device to device idx:  0 ()
INFO: "BM"  - Default device selected ()
INFO: "BM"  - Linking deinterleave pad src_0 to queueSinkPadL ()
INFO: "BM"  - link succeeded ()
INFO: "BM"  - Linking complete ()
INFO: "BM"  - Linking deinterleave pad src_1 to queueSinkPadR ()
INFO: "BM"  - link succeeded ()
INFO: "BM"  - Linking complete ()
INFO: "BM"  - emitting volume changed:  98 ()
INFO: "BM"  - Gst msg type:  262144  Gst msg name:  duration-changed ()
INFO: "BM"  - Gst msg type:  268435456  Gst msg name:  stream-start ()
INFO: "BM"  - Gst msg type:  524288  Gst msg name:  latency ()
INFO: "BM"  - Gst msg type:  2097152  Gst msg name:  async-done ()
INFO: "BM"  - Gst msg type:  2048  Gst msg name:  new-clock ()
INFO: "BM"  - AudioBackendGstreamer::stop( false ) called ()
INFO: "BM"  - AudioBackendGstreamer::stop -- Fading enabled.  Fading out audio volume ()
INFO: fadeOut(  true  ) called ()
INFO: "BM"  - Fader started ()
INFO: Timer fader - Current:  0.989898  Target:  0 ()
INFO: "BM"  - emitting volume changed:  93 ()
INFO: Timer fader - Current:  0.939898  Target:  0 ()
INFO: "BM"  - emitting volume changed:  88 ()
INFO: Timer fader - Current:  0.889898  Target:  0 ()
INFO: "BM"  - emitting volume changed:  83 ()
INFO: Timer fader - Current:  0.839898  Target:  0 ()
INFO: "BM"  - emitting volume changed:  78 ()
INFO: Timer fader - Current:  0.789898  Target:  0 ()
INFO: "BM"  - emitting volume changed:  73 ()
INFO: Timer fader - Current:  0.739898  Target:  0 ()
INFO: "BM"  - emitting volume changed:  68 ()
INFO: Timer fader - Current:  0.689898  Target:  0 ()
INFO: "BM"  - emitting volume changed:  63 ()
INFO: Timer fader - Current:  0.639898  Target:  0 ()
INFO: "BM"  - emitting volume changed:  58 ()
INFO: Timer fader - Current:  0.589898  Target:  0 ()
INFO: "BM"  - emitting volume changed:  53 ()
INFO: Timer fader - Current:  0.539898  Target:  0 ()
INFO: "BM"  - emitting volume changed:  48 ()
INFO: Timer fader - Current:  0.489898  Target:  0 ()
INFO: "BM"  - emitting volume changed:  43 ()
INFO: Timer fader - Current:  0.439898  Target:  0 ()
INFO: "BM"  - emitting volume changed:  38 ()
INFO: Timer fader - Current:  0.389898  Target:  0 ()
INFO: "BM"  - emitting volume changed:  33 ()
INFO: Timer fader - Current:  0.339898  Target:  0 ()
INFO: "BM"  - emitting volume changed:  28 ()
INFO: Timer fader - Current:  0.289898  Target:  0 ()
INFO: "BM"  - emitting volume changed:  23 ()
INFO: Timer fader - Current:  0.239898  Target:  0 ()
INFO: "BM"  - emitting volume changed:  18 ()
INFO: Timer fader - Current:  0.189898  Target:  0 ()
INFO: "BM"  - emitting volume changed:  13 ()
INFO: Timer fader - Current:  0.139898  Target:  0 ()
INFO: "BM"  - emitting volume changed:  8 ()
INFO: Timer fader - Current:  0.0898983  Target:  0 ()
INFO: "BM"  - emitting volume changed:  3 ()
INFO: Timer fader - Current:  0.0398983  Target:  0 ()
INFO: "BM"  - fader finished ()
INFO: fadeOut returned ()
INFO: "BM"  - AudioBackendGstreamer::stop -- Fading complete ()
INFO: "BM"  - AudioBackendGstreamer::stop -- Stoping playback ()
INFO: DlgCdg::setShowBgImage( true ) called ()
INFO: triggerBg called ()
INFO: DlgCdg::setShowBgImage( true ) called ()
INFO: "BM"  - AudioBackendGstreamer::stop -- Setting volume back to original setting:  98 ()
INFO: "BM"  - setVolume - setting to linear:  0.941192 ()
INFO: AudioFader set paused state to:  true ()
INFO: "BM"  - Initializing gst
 ()
INFO: "BM"  - setVolume - setting to linear:  0.941192 ()
INFO: AudioFader set paused state to:  false ()
INFO: "BM"  - Setting output device to device idx:  0 ()
INFO: "BM"  - Default device selected ()
INFO: "BM"  - Linking deinterleave pad src_0 to queueSinkPadL ()
INFO: "BM"  - link succeeded ()
INFO: "BM"  - Linking complete ()
INFO: "BM"  - Linking deinterleave pad src_1 to queueSinkPadR ()
INFO: "BM"  - link succeeded ()
INFO: "BM"  - Linking complete ()
INFO: "BM"  - emitting volume changed:  99 ()
INFO: "BM"  - Gst msg type:  262144  Gst msg name:  duration-changed ()
INFO: "BM"  - Gst msg type:  268435456  Gst msg name:  stream-start ()
INFO: "BM"  - Gst msg type:  524288  Gst msg name:  latency ()
INFO: "BM"  - Gst msg type:  2097152  Gst msg name:  async-done ()
INFO: "BM"  - Gst msg type:  2048  Gst msg name:  new-clock ()
INFO: "BM"  - AudioBackendGstreamer::stop( false ) called ()
INFO: "BM"  - AudioBackendGstreamer::stop -- Fading enabled.  Fading out audio volume ()
INFO: fadeOut(  true  ) called ()
INFO: "BM"  - Fader started ()
INFO: Timer fader - Current:  0.993288  Target:  0 ()
INFO: "BM"  - emitting volume changed:  94 ()
INFO: Timer fader - Current:  0.943288  Target:  0 ()
INFO: "BM"  - emitting volume changed:  89 ()
INFO: Timer fader - Current:  0.893288  Target:  0 ()
INFO: "BM"  - emitting volume changed:  84 ()
INFO: Timer fader - Current:  0.843288  Target:  0 ()
INFO: "BM"  - emitting volume changed:  79 ()
INFO: Timer fader - Current:  0.793288  Target:  0 ()
INFO: "BM"  - emitting volume changed:  74 ()
INFO: Timer fader - Current:  0.743288  Target:  0 ()
INFO: "BM"  - emitting volume changed:  69 ()
INFO: Timer fader - Current:  0.693288  Target:  0 ()
INFO: "BM"  - emitting volume changed:  64 ()
INFO: Timer fader - Current:  0.643288  Target:  0 ()
INFO: "BM"  - emitting volume changed:  59 ()
INFO: Timer fader - Current:  0.593288  Target:  0 ()
INFO: "BM"  - emitting volume changed:  54 ()
INFO: Timer fader - Current:  0.543288  Target:  0 ()
INFO: "BM"  - emitting volume changed:  49 ()
INFO: Timer fader - Current:  0.493288  Target:  0 ()
INFO: "BM"  - emitting volume changed:  44 ()
INFO: Timer fader - Current:  0.443288  Target:  0 ()
INFO: "BM"  - emitting volume changed:  39 ()
INFO: Timer fader - Current:  0.393288  Target:  0 ()
INFO: "BM"  - emitting volume changed:  34 ()
INFO: Timer fader - Current:  0.343288  Target:  0 ()
INFO: "BM"  - emitting volume changed:  29 ()
INFO: Timer fader - Current:  0.293288  Target:  0 ()
INFO: "BM"  - emitting volume changed:  24 ()
INFO: Timer fader - Current:  0.243288  Target:  0 ()
INFO: "BM"  - emitting volume changed:  19 ()
INFO: Timer fader - Current:  0.193288  Target:  0 ()
INFO: "BM"  - emitting volume changed:  14 ()
INFO: Timer fader - Current:  0.143288  Target:  0 ()
INFO: "BM"  - emitting volume changed:  9 ()
INFO: Timer fader - Current:  0.0932884  Target:  0 ()
INFO: "BM"  - emitting volume changed:  4 ()
INFO: Timer fader - Current:  0.0432884  Target:  0 ()
INFO: "BM"  - fader finished ()
INFO: fadeOut returned ()
INFO: "BM"  - AudioBackendGstreamer::stop -- Fading complete ()
INFO: "BM"  - AudioBackendGstreamer::stop -- Stoping playback ()
INFO: DlgCdg::setShowBgImage( true ) called ()
INFO: triggerBg called ()
INFO: DlgCdg::setShowBgImage( true ) called ()
INFO: "BM"  - AudioBackendGstreamer::stop -- Setting volume back to original setting:  99 ()
INFO: "BM"  - setVolume - setting to linear:  0.970299 ()
INFO: AudioFader set paused state to:  true ()
INFO: "BM"  - Initializing gst
 ()
INFO: "BM"  - setVolume - setting to linear:  0.970299 ()
INFO: AudioFader set paused state to:  false ()
INFO: "BM"  - Setting output device to device idx:  0 ()
INFO: "BM"  - Default device selected ()
INFO: "BM"  - Linking deinterleave pad src_0 to queueSinkPadL ()
INFO: "BM"  - link succeeded ()
INFO: "BM"  - Linking complete ()
INFO: "BM"  - Linking deinterleave pad src_1 to queueSinkPadR ()
INFO: "BM"  - link succeeded ()
INFO: "BM"  - Linking complete ()
INFO: "BM"  - Gst msg type:  268435456  Gst msg name:  stream-start ()
INFO: "BM"  - Gst msg type:  262144  Gst msg name:  duration-changed ()
INFO: "BM"  - Gst msg type:  524288  Gst msg name:  latency ()
INFO: "BM"  - Gst msg type:  2097152  Gst msg name:  async-done ()
INFO: "BM"  - Gst msg type:  2048  Gst msg name:  new-clock ()
INFO: "BM"  - setVolume - setting to linear:  0.884736 ()
INFO: "BM"  - setVolume - setting to linear:  0.729 ()
INFO: "BM"  - setVolume - setting to linear:  0.531441 ()
INFO: "BM"  - setVolume - setting to linear:  0.373248 ()
INFO: "BM"  - setVolume - setting to linear:  0.274625 ()
INFO: "BM"  - setVolume - setting to linear:  0.195112 ()
INFO: "BM"  - setVolume - setting to linear:  0.157464 ()
INFO: "BM"  - emitting volume changed:  53 ()
INFO: "BM"  - setVolume - setting to linear:  0.148877 ()
INFO: "BM"  - setVolume - setting to linear:  0.140608 ()
INFO: "BM"  - setVolume - setting to linear:  0.132651 ()
INFO: "BM"  - setVolume - setting to linear:  0.097336 ()
INFO: "BM"  - setVolume - setting to linear:  0.091125 ()
INFO: "BM"  - emitting volume changed:  44 ()
INFO: "BM"  - setVolume - setting to linear:  0.085184 ()
INFO: "BM"  - setVolume - setting to linear:  0.079507 ()
INFO: "BM"  - setVolume - setting to linear:  0.074088 ()
INFO: "BM"  - emitting volume changed:  41 ()
INFO: "BM"  - setVolume - setting to linear:  0.068921 ()
INFO: "BM"  - setVolume - setting to linear:  0.074088 ()
INFO: "BM"  - emitting volume changed:  41 ()
INFO: "BM"  - setVolume - setting to linear:  0.068921 ()
INFO: "BM"  - setVolume - setting to linear:  0.074088 ()
INFO: "BM"  - emitting volume changed:  41 ()
INFO: "BM"  - setVolume - setting to linear:  0.068921 ()
INFO: "BM"  - setVolume - setting to linear:  0.074088 ()
INFO: "BM"  - setVolume - setting to linear:  0.079507 ()
INFO: "BM"  - setVolume - setting to linear:  0.091125 ()
INFO: "BM"  - emitting volume changed:  44 ()
INFO: "BM"  - setVolume - setting to linear:  0.085184 ()
INFO: "BM"  - setVolume - setting to linear:  0.110592 ()
INFO: "BM"  - AudioBackendGstreamer::stop( false ) called ()
INFO: "BM"  - AudioBackendGstreamer::stop -- Fading enabled.  Fading out audio volume ()
INFO: fadeOut(  true  ) called ()
INFO: "BM"  - Fader started ()
INFO: Timer fader - Current:  0.48  Target:  0 ()
INFO: "BM"  - emitting volume changed:  43 ()
INFO: Timer fader - Current:  0.43  Target:  0 ()
INFO: "BM"  - emitting volume changed:  37 ()
INFO: Timer fader - Current:  0.38  Target:  0 ()
INFO: "BM"  - emitting volume changed:  33 ()
INFO: Timer fader - Current:  0.33  Target:  0 ()
INFO: "BM"  - emitting volume changed:  27 ()
INFO: Timer fader - Current:  0.28  Target:  0 ()
INFO: "BM"  - emitting volume changed:  22 ()
INFO: Timer fader - Current:  0.23  Target:  0 ()
INFO: "BM"  - emitting volume changed:  17 ()
INFO: Timer fader - Current:  0.18  Target:  0 ()
INFO: "BM"  - emitting volume changed:  12 ()
INFO: Timer fader - Current:  0.13  Target:  0 ()
INFO: "BM"  - emitting volume changed:  7 ()
INFO: Timer fader - Current:  0.08  Target:  0 ()
INFO: "BM"  - emitting volume changed:  2 ()
INFO: Timer fader - Current:  0.03  Target:  0 ()
INFO: "BM"  - fader finished ()
INFO: fadeOut returned ()
INFO: "BM"  - AudioBackendGstreamer::stop -- Fading complete ()
INFO: "BM"  - AudioBackendGstreamer::stop -- Stoping playback ()
INFO: DlgCdg::setShowBgImage( true ) called ()
INFO: triggerBg called ()
INFO: DlgCdg::setShowBgImage( true ) called ()
INFO: "BM"  - AudioBackendGstreamer::stop -- Setting volume back to original setting:  48 ()
INFO: "BM"  - setVolume - setting to linear:  0.110592 ()

**Comment by coyote1357** [comment]
1.5.62 is building now for all platforms.  Contains a potential fix for this issue.
