### ISSUE TITLE
Open KJ 1.5.82

### ISSUE THREAD

**Issue by vipermetcaff** [OpenKJ/OpenKJ#168]

**Comment by vipermetcaff** [comment]
https://www.youtube.com/watch?v=XKOCoB0OrKM&feature=youtu.be
Broken Cdg window

**Comment by coyote1357** [comment]
I'm aware of things being broken badly in versions above 1.5.70 at the moment.  Lots of re-work going on there.  I don't recommend running any newer unstable versions until I've posted that it's safe on the project's Facebook page.
