### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by vipermetcaff** [OpenKJ/OpenKJ#18]
run the incoming request and songbook from a local http server on the  host machine using a router or a wifi if you dont have any internet connection  for people to connect to so they can use their phone or ipad  to connect to  to serve the song book 

another idea i had is auto play  a karaoke song an a set interval  when the song ends then after so many seconds the next song starts
and an a another idea i had if the request page pull all of the songs that are on the host machine and display them so you can pick a song from them  incase you dont know the song

**Comment by coyote1357** [comment]
Sorry for the delay, I was taking a break from the project to catch up on reading and for the holiday.

The request server would be doable, but it would be a separate project as the OpenKJ software only implements the client side of the API.  

The idea of playing songs via the request server is beyond my web development skills.  Most professional KJs have song collections in the hundreds of gigabytes if not over a terabyte, and transferring all of that to a separate request server via a REST API would be unrealistic.  The only way I could see it working is if the request server were running on a system that already has all of the karaoke files (either the one used to host or another one).  Even then, there is, to my knowledge, nothing out there with support for playing mp3+g zip files in the browser, so they would need to be transcoded to a streamable video format on demand, somehow.

The idea of doing auto-play after a delay is something I could work in.

**Comment by vipermetcaff** [comment]
Ya have a local request server so if the venue doesnt have internet access you can still use the song book. Like useing a roughter as the access point for the song book

**Comment by karaokeniagara** [comment]
I noticed in the singer Que (Bottom Left Side) and also (Bottom right side player list) 
Auto plays the "next song when it is double clicked.

If you can simply create a popup box letting KJ know that the "now playing" song will be interrupted. would be perfect.

or just disable double click to play will also work.
--

**Comment by coyote1357** [comment]
Added @karaokeniagara requested popup/warning on song interruption feature in v1.1.23

**Comment by coyote1357** [comment]
Experimental support for automatically playing the next song has been added.  Under settings, there is now an "Other" category and you can find the settings in there for enabling it and controlling the delay between songs.

**Comment by coyote1357** [comment]
And now there is also an optional next singer alert that can be displayed on the CDG output window. It shows next singer, song, and does a countdown to when the song will start playing.

**Comment by coyote1357** [comment]
Just a heads up to anyone following this thread, I've received a report of autoplay not working properly on Windows.  I'm investigating.

**Comment by coyote1357** [comment]
The issues that we're reported with autoplay have been fixed.  This feature should be good to go.
