### ISSUE TITLE
Bug: OpenKJ - MP4 videos not seeking properly

### ISSUE THREAD

**Issue by backstagekaraoke** [OpenKJ/OpenKJ#181]
OpenKJ

When seeking an MP4 video (and maybe other formats) it cause the audio to stop until whatever is happening in the background realises and catches up. Happens seeking forward and backward.

Whilst there is really no situation that would warrant skipping ahead of back, as you would simply just restart the song, I believe there is some sort of glitch, as seeking in a player such as VLC does not have the audio delay issue with the same files.

**Comment by coyote1357** [comment]
This one I'm aware of, but unfortunately seems to be a problem in gstreamer related to the complexity of the audio pipeline used in OpenKJ.  I'ts a "can't fix" at the moment.
