### ISSUE TITLE
Bug: OpenKJ - Tracks marked BAD and Remove doesn't remove audio file

### ISSUE THREAD

**Issue by backstagekaraoke** [OpenKJ/OpenKJ#184]
Issue:

When you mark a track as BAD and choose to remove the file from disk, it only removes the CDG file, it leaves the corresponding audio file behind. Not sure if this is by design. 

I guess I can see the thinking behind this, if for example, you wanted to 'fix' the CDG file and then just add it back in, the audio file would still be there. However, that scenario is slim at best.

Suggestion:

Have two options:

1. Remove only CDG file
2. Remove both CDG and Audio file

If they do this for an MP4 (or other video file) it just advises "This is a video file, would you like to remove it from disk?" etc.

**Comment by coyote1357** [comment]
This is an oversight on my part.  It's supposed to remove both.  I just apparently forgot to actually add the code to remove the audio file.
