### ISSUE TITLE
OpenKJ - M4V video files not recognized for import, but will play if dropped in

### ISSUE THREAD

**Issue by backstagekaraoke** [OpenKJ/OpenKJ#186]
OpenKJ v1.5.120
I have only been able to test this out on OpenKJ for MacOS at this point.

When you try an import any m4v video files ... nothing happens. They do not get imported, and nothing actually shows up in the debug logs, it basically looks like it does nothing.

However if you drag and drop an m4v file into the song queue, it plays without issues.

Maybe m4v files are simply not in the extension types to recognize during import?

**Comment by coyote1357** [comment]
1.5.125 should add support for these files to the db update logic.  I just don't have any m4v files so I can't test myself.

**Comment by backstagekaraoke** [comment]
This has now been resolved
