### ISSUE TITLE
feature Request

### ISSUE THREAD

**Issue by vipermetcaff** [OpenKJ/OpenKJ#189]
@coyote1357 it would be nice to have the database save in the openkj folder instead of the app data folder  on windows in case if you have to redo windows so you  don't have to pull it over

**Comment by coyote1357** [comment]
This isn't viable since on many systems the user running OpenKJ doesn't
have write access to the Program Files folder.

**Comment by vipermetcaff** [comment]
i have my open kj on another partition  on my windows computer would like to have the database  where open kj resides folder path inside  D:\APPS\OKJ  piont to the database inside the folder and have openkj look there

**Comment by vipermetcaff** [comment]
@coyote1357

**Comment by backstagekaraoke** [comment]
@vipermetcaff - bigger ticket items to get done at the moment, to improve much more important functionality with OKJ.
