### ISSUE TITLE
installer open kj 32 bit windows

### ISSUE THREAD

**Issue by vipermetcaff** [OpenKJ/OpenKJ#19]
@coyote1357 
 got a dell latitude 2100 with a 32 bit processor and installer throws this error
![2](https://user-images.githubusercontent.com/6171564/32985096-af447cec-cc6f-11e7-8588-610946d62344.png)
![untitled](https://user-images.githubusercontent.com/6171564/32985097-af81f176-cc6f-11e7-9d7a-8dc2b363ac24.png)

**Comment by coyote1357** [comment]
Apologies for the delay, I was taking a bit of a break from the project to catch up on reading and to enjoy the holiday.

I will look into creating an automated build environment to produce 32-bit binaries and installers for Windows.  However, I'm not sure how well OpenKJ will perform an a system old enough that it doesn't support 64bit, it may be underpowered.  I don't have any old hardware lying around that I can test on.

One currently available option is to run it under Linux, as 32bit packages are already automatically generated for rpm and deb based Linux distributions (Fedora, Debian, Ubuntu, Mint, Elementary, etc) by COPR and launchpad.

**Comment by coyote1357** [comment]
A test Windows 32bit installer is up under unstable downloads on the OpenKJ website.  It is untested as I don't have any 32 bit Windows instances.  Give it a shot and let me know if it works.

**Comment by coyote1357** [comment]
Windows 32 bit versions are now automatically built and installers are generated for them.
