### ISSUE TITLE
ssl error

### ISSUE THREAD

**Issue by vipermetcaff** [OpenKJ/OpenKJ#20]
![1](https://user-images.githubusercontent.com/6171564/33961792-8be602ce-e00c-11e7-946c-dab22cddaa57.png)

**Comment by coyote1357** [comment]
Errr... woops... I accidentally let the songbook.openkj.org SSL cert expire. 

If you go to settings and tick the "Ignore SSL errors" box it should start working until I can get the SSL cert updated.

**Comment by vipermetcaff** [comment]
yep that worked

**Comment by coyote1357** [comment]
SSL certificate has been updated, site is operating normally now.
