### ISSUE TITLE
Drag and drop zip files

### ISSUE THREAD

**Issue by vipermetcaff** [OpenKJ/OpenKJ#200]
1.6.7 stable 
can not drag an drop  zip or cdg files on to the song queue 

i m running an older version and drag an drop works

**Comment by backstagekaraoke** [comment]
@vipermetcaff - CDGs can be drag and dropped, 1.8.4 introduced CDG+WAV as well .... can you please confirm on both 1.8.4 stable, and the latest unstable and confirm CDG drag and drop, and also let us know if ZIPs also work.

**Comment by ILightburn** [comment]
I've validated that this is working as expected on all of my test systems
