### ISSUE TITLE
Allow Regular Singer as option in Request form

### ISSUE THREAD

**Issue by generalredneck** [OpenKJ/OpenKJ#201]
I use the Request dialog a lot from an online songbook when I do a gig. I do often have regulars that use the app to make the request too because they will be off at the bar or what not. A lot of the time I don't know that they are there. The challenge is that the first time this happened... I had to be with it enough to recognize my regular's name... with the Incoming request form still open (or close it) and then go to Karaoke->Regulars to bring up the window, add the person, then go back to the Requests dialog to click the "Add Song" button. It would be nice if one of the "Add to Singer" would recognize the existing singer or have a list of regulars for you to select from. Or maybe a "regulars" button so that you can popup that dialog then and there whiout the window fumbling as you seen me do in the following screen capture :P.
![Peek 2020-02-23 14-10](https://user-images.githubusercontent.com/526491/75119251-b43fc900-5646-11ea-9631-7445af47db11.gif)

**Comment by backstagekaraoke** [comment]
incoming requests already match on existing singers based on the name being sent through. Another feature is going to look at additional methods to identify patrons and their devices for increased functionality.
