### ISSUE TITLE
Songbook Creator - can't select variations from font family in Mac OS

### ISSUE THREAD

**Issue by BeansIsFat** [OpenKJ/OpenKJ#204]
In Songbook Creator, the font selector only shows base font for a font family on Mac OS, even when there are multiple typefaces that are part of that family (bold, italic, light, etc.). This effectively means you can only use the base font and even the Bold checkbox doesn't work for some fonts.

The font selector for the Ticker is OS native and allows for the selection of any version in a font family. Would it be possible to use the same font selector for Songbook Creator?

I've tried this on the latest stable (1.4.8) and unstable (1.7.41) versions.

**Comment by backstagekaraoke** [comment]
Printed songbooks are a thing of the past now, almost everyone has a phone so they can use the Songbook app. If they don't have a phone, they can use a friends phone or if the host provides kiosk tablets they can use those.

The songbook creator will be getting phased out of OpenKJ or will only remain as a legacy item with no further work on it.

Suggest using the Songbook app or the Songbook Kiosk app moving forward.

**Comment by BeansIsFat** [comment]
That's unfortunate. I use the standalone request server but I like having a PDF songbook linked from the home page. I find it's easier for singers to browse the available songs this way and maybe find something they want to sing but weren't thinking of.
