### ISSUE TITLE
Settings - Ticker

### ISSUE THREAD

**Issue by oasiz** [OpenKJ/OpenKJ#21]
The Ticker (checkbox) setting does not save.

To reproduce, go to Tools>Settings>Video, un-check "Ticker", click "close" and then restart the program.

Ticker will re-appear.

Windows 10, OpenKJ-1.1.20-64bit.

**Comment by coyote1357** [comment]
New version 1.1.25 has been released to fix this and is available for download on the openkj.org website, please download, install, and verify.

Thanks for the report!

**Comment by oasiz** [comment]
This version fixes the issue, thanks!
