### ISSUE TITLE
Updated to 1.8.3 on Mac OS, worked several times but now won't open.

### ISSUE THREAD

**Issue by daveError** [OpenKJ/OpenKJ#219]
Hi there,

I opened OpenKJ up yesterday and received a notification of an updated version being available. I upgraded with the hope that some of the bugs would be ironed out.

I launched the application a number of times, running it through its paces, but all of a sudden it won't open up.

I remember having an issue like this with the older version, the fix being to delete the file $HOME/Library/Preferences/org.openkj.OpenKJ.plist
But doing that did not help. Is there a new preferences file location being used? Could this be another issue?

Thank you.

I'm using a Late 2013 MacBook Pro Retina 15" running macOS Catalina 10.15.7.

**Comment by coyote1357** [comment]
Try removing /Users/<your home dir>/Library/Application Support/OpenKJ/openkj.ini
If something got corrupted in the program settings that should resolve it.

You may also try removing /Users/<your home dir>/Library/Preferences/org.openkj.OpenKJ.plist

**Comment by daveError** [comment]
Well, what do you know? That did it. Thank you!

**Comment by coyote1357** [comment]
No problem.  Which one fixed it?  Or did you do both before trying to run it again?  Hopefully I'll eventually figure out why it does that occasionally on macOS.  It's just hard to track down because it only happens randomly every once in a while.

**Comment by daveError** [comment]
Just deleting the .ini file seemed to do the trick. I decided to get all my settings how I wanted them and then save a copy of the .ini in its working state, that way if this happens again I can just overwrite the failed copy with one that was known to work. If this problem does happen again, I could possibly save a copy of the failed file and the working one and get them to you to see if you can spot the point of failure if that would help.

**Comment by coyote1357** [comment]
That would definitely be helpful.  Hopefully I'll be able to spot what's out of whack.

**Comment by daveError** [comment]
Hey, I just figured I'd follow through and send you the ini that makes my copy of OpenKJ crash, file extension changed to .txt.
The file openkj-backup.txt is a copy of the file I use to fix this issue. When I replace the "bad" file with it, OpenKJ works again.
The file openkj-crashes.txt is the file that causes it to crash.

[openkj-backup.txt](https://github.com/OpenKJ/OpenKJ/files/5946315/openkj-backup.txt)
[openkj-crashes.txt](https://github.com/OpenKJ/OpenKJ/files/5946316/openkj-crashes.txt)

Hope this helps at least a little.

**Comment by backstagekaraoke** [comment]
@daveError I believe this was fixed in 1.8.4 onwards, when we moved from plist to conf/ini based settings file format, or possibly even just in the mac unstable at the moment. 

test 1.8.4 or the latest unstable and report back.

**Comment by backstagekaraoke** [comment]
closing as no response from user in nearly a month.
