### ISSUE TITLE
Settings - Ticker Height

### ISSUE THREAD

**Issue by oasiz** [OpenKJ/OpenKJ#22]
Dropping the ticker height to 0 (or blank) crashes the system completely and (for me at least) requires a full software re-installation.

Windows 10, OpenKJ-1.1.25-64bit.

**Comment by coyote1357** [comment]
Added a range check to the ticker height adjustment to not allow values < 1.  New version has been built and uploaded to the website v1.1.26

Give it a shot and see if it prevents the behavior for you.

Thanks for the bug report!

**Comment by oasiz** [comment]
Tested and works perfectly. Thanks for the update :-)
