### ISSUE TITLE
BUG: 1.9.58 - Break Music not fading back in after each song

### ISSUE THREAD

**Issue by backstagekaraoke** [OpenKJ/OpenKJ#224]
Linux - 1.9.58

Steps to reproduce:
Set your break music volume
Start playing break music
either let the song play through or drag slider through to just before end
wait for the break music to fade out
next song will start playing, but no volume
adjust the break music volume slider slightly
break music volume returns

here is the log file

[openkj-debug-2021-03-13-1338-log.log](https://github.com/OpenKJ/OpenKJ/files/6134134/openkj-debug-2021-03-13-1338-log.log)

**Comment by ILightburn** [comment]
Able to duplicate.  Only happens when fader is enabled on break music in settings.  As a stopgap people can disable the fader for break music.  Won't prevent the fade in/out of break music around karaoke songs, as that's a separate thing.  Will only affect stopping or pausing a break song.

**Comment by ILightburn** [comment]
Should be fixed in the latest unstable versions.
