### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by oasiz** [OpenKJ/OpenKJ#23]
1. Strip out special characters when searching.
e.g Searching for "aint no mountain high enough" matches "ain't no mountain high enough".
2. Option to auto-play songs in "next up" (box where songs are dragged in to).
3. Option to automatically remove songs from "next up" box when played.

**Comment by coyote1357** [comment]
I'll think over # 1.  Just a note on searching, though.  If I were searching for the example you gave, I'd search for "ain no moun high", "moun high aretha", or some similarly abbreviated version.  The search in OpenKJ does partial matches on any part of the artist, title, or discid with the search terms given.

On 2 & 3, are you talking about inside the break music player portion?

**Comment by oasiz** [comment]
1. OK no worries. I'm fine searching myself but it's if/when others (family etc) are using the system, I think stripping out non-alphanumeric chars from searches would be an improvement.
 2/3. Not the break music, the section to the bottom right. Currently I'm dragging songs from the search pane to there and double clicking to begin.

**Comment by coyote1357** [comment]
Oh, got you.  You're talking about the singer's queue. I thought you were talking about adding something new to drag to.  

Basically automatically play the next queued karaoke song... presumably after a certain delay between songs?

**Comment by oasiz** [comment]
Apologies for the delay in response.

Yes that's correct, an option to automatically carry on and play the next queued song would be excellent, and possibly a setting to determine the delay (in seconds).

That and an option to remove the song from the singers queue once it's been played, would be an excellent addition.

Absolutely loving how easy the system is, how you can just drag a bunch of tracks into the singers queue and play without even needing to assign a name/singer - makes things so simple.

**Comment by coyote1357** [comment]
Experimental support for automatically playing the next karaoke song has been added.  Under settings, there is now an "Other" category and you can find the settings in there for enabling it and controlling the delay between songs.  The version with the support added is 1.1.32

I'm not sure I want to implement the "delete on play" functionality, since that would conflict with the way regular singer tracking works.  But, as implemented, auto-advance will not play a song if it has already been played, it will skip to the first un-played song in the singer's queue, so it should work the way I think you want it to without the song removal.

**Comment by coyote1357** [comment]
Also, if you manually stop a song by hitting the stop button, or hit the stop button during the delay between songs, it will cancel autoplay mode until the next song is played manually.

**Comment by coyote1357** [comment]
And now there is an optional next singer alert that can be displayed on the CDG output window.  It shows next singer, song, and does a countdown to when the song will start playing.

**Comment by oasiz** [comment]
Great stuff @coyote1357 nice update.

I'd still like to see the removal of special characters (particularly the "'" symbol) during searches, as I've a lot of files where "It's" is spelled "Its", "There's", "Theres" etc etc.

Searching myself is easy, but my whole family will likely use the system during parties to give me a break, and that would make it easy for everyone.

It's certainly not mission-critical though, so if it is a particularly hard feature to implement then please don't waste ages doing it!!

**Comment by coyote1357** [comment]
Just a heads up, I've received a report of autoplay not working properly on Windows.  I'm investigating.

**Comment by coyote1357** [comment]
The issues reported with autoplay have been fixed.  This feature should be good to go.

**Comment by coyote1357** [comment]
In version 1.1.54, an option has been added to ignore apostrophes in karaoke searches.  It's under the "Other" section in settings.

**Comment by oasiz** [comment]
Tested and working perfectly, thanks for adding this!
