### ISSUE TITLE
Feature request - Double click track

### ISSUE THREAD

**Issue by oasiz** [OpenKJ/OpenKJ#24]
Very minor feature request/improvement, the ability to double click on a track/song from the search results to have it added to the song next-up queue.

**Comment by oasiz** [comment]
... and/or have it as an option in the right-click context menu.

**Comment by oasiz** [comment]
Strange - this wasn't working for me yesterday but (after re-starting the program) have just discovered that a double click is in fact adding the track to the queue. Apologies, ignore this!

**Comment by oasiz** [comment]
This problem is back, and is seemingly intermittent.

Let me just re-open this for now and I'll try and get you some steps together to reproduce it yourself.

As things stand I can no longer double-click on a search result to have it applied to the next-up singer queue...

**Comment by coyote1357** [comment]
Note that double clicking a song adds it to the queue of the currently selected singer in the rotation list.  If you don't have a singer selected, it won't do anything.

**Comment by oasiz** [comment]
Hmm, I think I might have got mixed up then!

Yes that works perfectly if using the Singer queue.

To be honest I'd forgotten about that, as in our little set-up with only 2-4 singers I cut out that entirely (completely hide that box) and drag the songs straight into the queue.

![image](https://user-images.githubusercontent.com/2811813/34247608-0700b732-e62b-11e7-910e-4907e195592b.png)

I'd quite like to be able to double click and have the songs appear straight in there, but I appreciate my case is unique and you can't please everyone!

Feel free to close this if you feel we're done here :-)

**Comment by oasiz** [comment]
Workaround!

I can create a singer (called "Group" etc), select it and then hide the singer box. All subsequent double clicks put the songs in the "Group" next-up queue.

Quite simple really, haha!
