### ISSUE TITLE
Feature Request: Flatpak version

### ISSUE THREAD

**Issue by 12people** [OpenKJ/OpenKJ#244]
It'd be nice if a Flatpak version of the app was offered for Linux.

The advantage would be higher security (as Flatpak apps are sandboxed) as well as potentially lower Linux maintenance (as the app would be built against one consistent set of libraries and wouldn't have to be built for each major distro separately).

**Comment by ILightburn** [comment]
I actually love this idea.  I just have no idea how to build flatpaks. lol

I briefly looked into it back when flatpaks first became a thing but couldn't find any good walkthroughs at the time.  Looked into snaps as well with the same result. I'll revisit the idea.

**Comment by 12people** [comment]
Great! :)

I definitely recommend checking out the official [Flatpak docs](https://docs.flatpak.org/en/latest/first-build.html).

I also recommend looking at the apps on [Flathub](https://flathub.org/) that use similar technologies. On the app's detail page, just click "See details" under "Publisher" and that should link you to the official Flathub repo for that app. Here is the [Flatpak repo for MuseScore](https://github.com/flathub/org.musescore.MuseScore/blob/master/org.musescore.MuseScore.yaml), for example, which also uses Qt. (It's more on the complex side, I imagine OpenKJ's Flatpak might be much simpler.)

As for Snaps, I wouldn't recommend them — their back-end is proprietary and tied to Canonical, so distros are predominantly going with Flatpak. (Even popular Ubuntu-based distros like Linux Mint or Elementary are going with Flatpak rather than snap, with the former [sharply criticizing Snaps](https://www.theregister.com/2020/06/02/linux_mint_team_snap/) and forbidding the installation of snapd via the apt package manager.) I find that Snaps go against the FOSS philosophy and I wouldn't use them myself.

**Comment by ILightburn** [comment]
I spent a few hours looking into this.  Unfortunately none of the available runtimes appear to provide both Qt and GStreamer unless I'm missing something.  Looks like fedora has a way to convert RPMs in the official repos to a fedora based runtime, but I couldn't figure out how to get it to work with a COPR hosted repo.  I recognize that I could have it build either GST or Qt from source, but both tend to send you deep into dependency hell if you want to do source builds.

Still want to do this, and will do more research when I have more downtime, but this is probably gonna be on the back-burner for a while as I work on getting the next stable out and some higher priority features written unless you or someone else wants to get it working and contribute the config.

**Comment by ILightburn** [comment]
It's ALLIIIVVVVEEEEEE
https://flathub.org/apps/details/org.openkj.OpenKJ

**Comment by 12people** [comment]
Wonderful, it works!

Thanks a lot!
