### ISSUE TITLE
cmake build fails if QT6 is present

### ISSUE THREAD

**Issue by AThomsen** [OpenKJ/OpenKJ#245]
Cmake build fails if Qt6 is present on the system.

I believe it's due to https://github.com/OpenKJ/OpenKJ/blob/e7246d1eba5f5588b8b63fc090fd02630f87388b/CMakeLists.txt#L28 essentialy saying "use Qt6 if found, else Qt5". 

Then later, Qt5 is referenced directly, for instance in
https://github.com/OpenKJ/OpenKJ/blob/e7246d1eba5f5588b8b63fc090fd02630f87388b/CMakeLists.txt#L519

Removing "Qt6" from NAMES in line 28  fixed build on my system (Arch Linux).

**Comment by ILightburn** [comment]
Will modify.  The find_package line was boilerplate that was generated by Qt Creator when making the initial cmake file.

**Comment by ILightburn** [comment]
Should be fixed now
