### ISSUE TITLE
Feature request - Break Music

### ISSUE THREAD

**Issue by oasiz** [OpenKJ/OpenKJ#25]
Settings > Audio > Break Music tab.

A tick-box option to automatically start break music (assuming there's some in the play list) upon program start.

A request driven by pure laziness, as currently this requires doing manually each time the OpenKJ is loaded.

**Comment by coyote1357** [comment]
1.1.48 has the break music playback start on program launch feature added.  It's under the Other section in settings

**Comment by oasiz** [comment]
Excellent, this works perfectly. Thanks for adding, much appreciated!
