### ISSUE TITLE
File - Exit

### ISSUE THREAD

**Issue by oasiz** [OpenKJ/OpenKJ#26]
"Exit" menu item does not do anything.

OpenKJ v 1.1.26, Windows 10 (64 bit).

**Comment by coyote1357** [comment]
Should be fixed in 1.1.28

**Comment by coyote1357** [comment]
Also went ahead and made the normal "alt+f x" keyboard shortcut work for closing the software.  It's in 1.1.30

**Comment by oasiz** [comment]
Works now!
