### ISSUE TITLE
BUG: RegEx Custom Patterns not parsing properly in .34 and .35 unstable

### ISSUE THREAD

**Issue by backstagekaraoke** [OpenKJ/OpenKJ#268]
Windows 10, 20H2 (but assume it would be any version)
OKJ 2.1.34 & 2.1.35 unstable
2.1.33 doesn't have this issue.

Despite the RegEx test area showing that the regex pattern is correct, the end result is missing the SongID.

See video of what the issue is.

https://drive.google.com/file/d/1hvZJJ9g9hMECZ71WgNglAk3B5OsSVzGn/view?usp=sharing

Also you might want to look at issues #260 & #261 at the same time as they are both for RegEx stuff too

**Comment by AThomsen** [comment]
Fixed: https://github.com/AThomsen/OpenKJ/commit/1e26c4fb68534c02b42128f392b7a6229f291be6

**Comment by backstagekaraoke** [comment]
tested and confirm RegEx matching is now working correctly.
Closing issue.
