### ISSUE TITLE
Feature Request - Break Music DB Selection

### ISSUE THREAD

**Issue by oasiz** [OpenKJ/OpenKJ#27]
The ability to select multiple tracks from the Song Database/Search and drag them into the currently selected Playlist all at once.

As things stand (please correct me if I'm doing it wrong) this can only be done individually, which can be quite tedious if you're using multiple tracks.

**Comment by coyote1357** [comment]
I'll figure out how to do this.  As an FYI, you can just double click songs to add them to the current playlist.

**Comment by oasiz** [comment]
Yeah I've been double clicking them to add to the playlist. Thanks for looking into this! :-)

**Comment by coyote1357** [comment]
This feature has now been added as of version 1.1.92
