### ISSUE TITLE
Feature Request - Removal Warning

### ISSUE THREAD

**Issue by oasiz** [OpenKJ/OpenKJ#28]
Removing non-played track from the karaoke song queue could have a "This track hasn't been played - are you sure?" type warning.

Obviously this might not be ideal for everyone, so potentially it could be a checkbox setting.

"Display warning when removing non-played song from queue?" Yes/No.

**Comment by coyote1357** [comment]
Feature added, give it a shot and let me know if it satisfies the request.

**Comment by oasiz** [comment]
Hi, thanks for adding this!

I've tested the feature and the "Removing un-played song from queue" warning/alert always shows up, even after the song has been played (Windows 10, 64 bit OpenKJ edition).

**Comment by coyote1357** [comment]
Woops, must have forgotten a conditional.  I'll look at it.

**Comment by coyote1357** [comment]
Yep, that was it.  Version 1.1.57 should fix it.
