### ISSUE TITLE
other OpenKJ software ideas

### ISSUE THREAD

**Issue by vipermetcaff** [OpenKJ/OpenKJ#29]
have a rest button to rest the songs that already have been played down by the in the singer que
and a Full screen button for the karaoke window and a button to turn off autoplay without going into settings

**Comment by coyote1357** [comment]
I don't want to crowd the main window UI anymore than it is to keep it as usable as possible on 720p displays.  But I could add a "Clear all played status" menu item to the right click menu that displays on queue items.  Similarly I could add a toggleable menu item to the Karaoke menu in the main window's menubar for controlling autoplay.  I'll play around with some ideas for fullscreening the CDG display via a UI button. Maybe something that only displays when you hover your mouse over the window.

**Comment by vipermetcaff** [comment]
here is something might work shift click select more then one one song you already have toggle played  in the right click menu that would work for me

**Comment by vipermetcaff** [comment]
i just figured out to make the window full  screen if i right click inside the window it goes full screen

**Comment by coyote1357** [comment]
In the latest version, if you hover over the CDG output, a button should pop up that allows you to switch between fullscreen and windowed.

**Comment by coyote1357** [comment]
Also, autoplay is now toggleable via the Karaoke menu on the main application menu.

**Comment by Smoothedge69** [comment]
Hi. Cool program you got there. I notice that there is a pitch changer, but no tempo change, or a sync adjustment, for syncing lyrics to music. Would these be things you will be adding in the future? I like the idea of the online songbook feature, but I do not quite understand how, or if it works. Thanks.

**Comment by coyote1357** [comment]
Hello @Smoothedge69,
Thanks :)  Both a tempo change and a music/CDG sync offset should be possible.

For the sync offset, are you thinking of this as a global setting? To adjust for any delays in your audio output chain?

I need to write documentation on the songbook thing.  It works like this:
Sign up at songbook.openkj.org using a Google acct.
Add a venue on the website.
Copy the API key generated for your acct on the website to API key field in the network section in settings in OpenKJ.
Open the remote requests dialog by going to Karaoke->Incoming Requests
Click the update remote DB button to transfer your song db info to the web service
Select a venue you added on the website from the venue drop-down and toggle the Accepting check box on to enable incoming requests, then dismiss the incoming requests dialog
In a browser, go to the search URL listed for your venue on your account page on songbook.openkj.org
Search for and find and submit a song following the prompts
It should pop up the incoming requests dialog in OpenKJ automatically and show the request within a few seconds of the request being entered.

**Comment by coyote1357** [comment]
Version 1.1.59 adds a sync offset option

**Comment by coyote1357** [comment]
@vipermetcaff  - Version 1.1.62 adds multi-select played status toggle in singer queue

**Comment by coyote1357** [comment]
@Smoothedge69 - Version 1.1.63 adds tempo control.
