### ISSUE TITLE
Crash Report - Mac OSX

### ISSUE THREAD

**Issue by djjimi** [OpenKJ/OpenKJ#31]
The following crash report was generated after installing OpenKJ-1.1.54-unstable-osx-installer.dmg:

Process:         launchd [369]
Path:            /Applications/OpenKJ.app/Contents/MacOS/OpenKJ
Identifier:      org.openkj.OpenKJ
Version:         ??? (???)
Code Type:       X86-64 (Native)
Parent Process:  launchd [200]

Date/Time:       2017-12-29 16:00:19.649 -0800
OS Version:      Mac OS X 10.6.8 (10K549)
Report Version:  6

Interval Since Last Report:          91933 sec
Crashes Since Last Report:           34
Per-App Crashes Since Last Report:   2
Anonymous UUID:                      5B488896-5244-493C-BAA4-90CEB20C0CD5

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0xfffffffffffffff8
Crashed Thread:  Unknown

Backtrace not available

Unknown thread crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000055  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x0000000000000000
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x00007fff5fc01028  rfl: 0x0000000000010203  cr2: 0xfffffffffffffff8

Binary images description not available

Model: MacBook7,1, BootROM MB71.0039.B0B, 2 processors, Intel Core 2 Duo, 2.4 GHz, 4 GB, SMC 1.60f6
Graphics: NVIDIA GeForce 320M, NVIDIA GeForce 320M, PCI, 256 MB
Memory Module: global_name
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x93), Broadcom BCM43xx 1.0 (5.10.131.42.4)
Bluetooth: Version 2.4.5f3, 2 service, 12 devices, 1 incoming serial ports
Network Service: AirPort, AirPort, en1
Serial ATA Device: TOSHIBA MK2555GSXF, 232.89 GB
Serial ATA Device: MATSHITADVD-R   UJ-898
USB Device: BUP Slim BK, 0x0bc2  (Seagate LLC), 0xab24, 0x26400000 / 2
USB Device: Built-in iSight, 0x05ac  (Apple Inc.), 0x8507, 0x24600000 / 2
USB Device: BRCM2070 Hub, 0x0a5c  (Broadcom Corp.), 0x4500, 0x06600000 / 3
USB Device: Bluetooth USB Host Controller, 0x05ac  (Apple Inc.), 0x8218, 0x06630000 / 5
USB Device: Apple Internal Keyboard / Trackpad, 0x05ac  (Apple Inc.), 0x0236, 0x06300000 / 2

**Comment by coyote1357** [comment]
Does it crash every time you try to start it?

**Comment by djjimi** [comment]
I've tried about a dozen times so far... and it crashes every time.  Could it be the OS on this machine is just too old?

**Comment by coyote1357** [comment]
Maybe?  It's built on High Sierra (10.13.2) with the latest version of xcode, and you appear to be running Snow Leopard (10.6.3).  I honestly don't know enough about Mac to know whether that would be an issue.  My only Mac experience is from setting up a MacBook Air I bought specifically for the purpose of figuring out how to compile and package OpenKJ for Mac.

Can you run "/Applications/OpenKJ.app/Contents/MacOS/OpenKJ" from a terminal window and paste me the output so I can see where the program is crashing during startup?

**Comment by coyote1357** [comment]
There was a bug that was causing crashes on Linux that could possibly be related to this.  Give the latest version a try and see if it's sorted out.

**Comment by coyote1357** [comment]
Closing due to possibly being fixed, it working on my Mac, and lack of response to the contrary
