### ISSUE TITLE
Segfault on Ubuntu artfull (17.10)

### ISSUE THREAD

**Issue by benoitg** [OpenKJ/OpenKJ#32]
Crashes when installed from the ppa, including a clean install on a different computer.

When installed from source, here is a bactrace:

(gdb) run
Starting program: /home/benoitg/development/OpenKJ/OpenKJ/OpenKJ 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe6ed5700 (LWP 29297)]
[New Thread 0x7fffda171700 (LWP 29298)]
[New Thread 0x7fffce2b1700 (LWP 29299)]
Initial volumes - K:  50  BM:  0
Database schema version:  102
DlgCdg::setShowBgImage( true ) called
DlgCdg::setShowBgImage( true ) called
Initializing gst

[New Thread 0x7fffc3f33700 (LWP 29300)]
Initializing gst

AudioRecorder constructor called
AudioRecorder::initGStreamer() called
AudioRecorder::generateDeviceList() called
AudioRecorder - Initializing gstreamer
AudioRecorder - Creating elements

Thread 1 "OpenKJ" received signal SIGSEGV, Segmentation fault.
__strchr_avx2 () at ../sysdeps/x86_64/multiarch/strchr-avx2.S:57
57      ../sysdeps/x86_64/multiarch/strchr-avx2.S: No such file or directory.
(gdb) bt
#0  0x00007ffff3a76298 in __strchr_avx2 () at ../sysdeps/x86_64/multiarch/strchr-avx2.S:57
#1  0x00007ffff6fa533f in g_param_spec_pool_lookup () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#2  0x00007ffff6fa0ccd in g_object_set_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#3  0x00007ffff6fa18ac in g_object_set () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#4  0x0000555555641fc4 in AudioRecorder::initGStreamer() (this=0x5555567a91e0) at audiorecorder.cpp:68
#5  0x0000555555642fdf in AudioRecorder::AudioRecorder(QObject*) (this=0x5555567a91e0, parent=0x7fffffffdc20) at audiorecorder.cpp:214
#6  0x00005555555895c3 in MainWindow::MainWindow(QWidget*) (this=0x7fffffffdc20, parent=0x0) at mainwindow.cpp:171
#7  0x00005555555880f8 in main(int, char**) (argc=1, argv=0x7fffffffdea8) at main.cpp:34
(gdb)

**Comment by coyote1357** [comment]
Looks like it's crashing whilst setting up the gstreamer stuff.  Can you install all of the gstreamer1 packages to see if I'm just missing a dependency in the deb package config?

**Comment by coyote1357** [comment]
Disregard, I found the issue.  New version should be up in the PPA as soon as I can get the launchpad builds done.  Thank you for letting me know about this, btw :)

**Comment by coyote1357** [comment]
New deb packages are up.  Give it a shot and see if it fixes the crash.

**Comment by benoitg** [comment]
It does!  Thanks.

On December 29, 2017 6:35:42 PM EST, "T. Isaac Lightburn" <notifications@github.com> wrote:
>New deb packages are up.  Give it a shot and see if it fixes the crash.
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/OpenKJ/OpenKJ/issues/32#issuecomment-354512871

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by coyote1357** [comment]
Awesome :)  Thanks for verifying
