### ISSUE TITLE
Feature Request: Double Click to stop music

### ISSUE THREAD

**Issue by Mightywiz** [OpenKJ/OpenKJ#33]
it's way to easy to single click on stop accidentally, can you make it a double click to stop a song.  some of us old guy that have an itchy trigger finger can accidentally hit the stop when moving the mouse around the screen and there's nothing like abruptly stopping a singers performance.

**Comment by vipermetcaff** [comment]
or would a popup box giveing a warning do you want to stop the current song when the stop button is clicked

**Comment by coyote1357** [comment]
An optional confirmation box would be way easier to implement, would still have the button perform the way most people expect buttons to work, and should prevent the "woops" moment.  I'll throw that in.

**Comment by coyote1357** [comment]
Optional warning/confirmation added on stop or pause button press while a karaoke song is playing.  To enable it, go to the Other section in settings.
