### ISSUE TITLE
Bad karaoke file

### ISSUE THREAD

**Issue by altere987** [OpenKJ/OpenKJ#35]
Let me start off by saying, I've used Sax n Dottys for Windows for years with no problems so I know it's not my karaoke files. Copied all my karaoke zip files from my external (that works under windows) onto laptop running openkj, just upgraded Jan 2nd..

Several of my SC karaoke files come up with the Bad karaoke file: Zip file does not contain a valid karaoke track. CDG or audio file missing or corrupt.

I initially thought the transfer corrupted some files so I imported directly from the external drive with the same results. Unzipped the file as well, to make sure both files were in the zip.

altere@nerf ~ $ unzip SC8118-11\ -\ Sinatra\,\ Frank\ -\ My\ Way.zip 
Archive:  SC8118-11 - Sinatra, Frank - My Way.zip
Created By MP3+G Toolz .NET
  inflating: SC8118-11 - Sinatra, Frank - My Way.cdg  
  inflating: SC8118-11 - Sinatra, Frank - My Way.mp3

----------------
I'd like to get away from Windows completely as karaoke is the only thing I use it for currently but I can't if half my library won't work.

**Comment by coyote1357** [comment]
Something is definitely up here.  Can you send me one of the non-working zips to support@openkj.org so I can try to figure out what's going on?

**Comment by coyote1357** [comment]
From email communication, it was determined that the non-working zip files were using deflate64 compression, which isn't supported by miniz, the library OpenKJ uses for zip handling.

Need to make the zip handling error messages more meaningful, so I'm marking this as an enhancement ticket.  Also need to modify the db import zip validation logic check the compression method used and reject files using an unsupported compression method, noting why in the skipped files info dialog.

**Comment by vipermetcaff** [comment]
there sorry file size was two big


CONFIDENTIALITY NOTICE:
The contents of this email message and any attachments are intended solely
for the addressee(s)
and may contain confidential and/or privileged information and may be
legally protected from
disclosure. If you are not the intended recipient of this message or their
agent, or if this message
has been addressed to you in error, please immediately alert the sender by
reply email and then
delete this message and any attachments. If you are not the intended
recipient, you are hereby
notified that any use, dissemination, copying, or storage of this message
or its attachments is
strictly prohibited.

 Ryan Adams@ ryankaseyadams@gmail.com

On Thu, Jan 4, 2018 at 2:20 AM, T. Isaac Lightburn <notifications@github.com

**Comment by coyote1357** [comment]
DB import now validates that zips aren't using defalte64 (or any other unsupported compression method) before adding them to the db.  It also warns the user that the file is unsupported in the skipped files dialog that pops up when errors are detected after the db update process finishes.
