### ISSUE TITLE
Songbook API

### ISSUE THREAD

**Issue by altere987** [OpenKJ/OpenKJ#36]
Incoming Requests - Accept Requests should be set to un-ticked on startup I would think.

Secondary:
when re-loaded with it still ticked, multiple request boxes pop-up.
after using it and leaving it un-ticked, then reloading, re-ticking, multiple request boxes pop-up.

Third:
I can see this being used as an attack, can't delay from IP address as venues may let customers use their wifi, however an option from the API level to be able to set an interval on how often to check. And maybe an option to not even have the requests pop-up in the foreground, as I would normally close this window out. But if it was on a time interval, and I could set it to check every 5 minutes, 10 minutes, etc, the pop-up would be favorable. 

Fourth:
Should the song be removed from the requests list if it's actually added from clicking Add Song?

On Mint OS 18

**Comment by coyote1357** [comment]
Accept requests is set server-side when you toggle it inside the program.  When the program starts up, it just fetches the current enabled/disabled state from the server side.  If you disable requests before you close the program, it should be unchecked when you open it back up again.

The way the dialog pop-up works is that it checks server side for new requests every 10s (well, technically, it's just checking to see if a unique serial # has changed).  If new requests exist, it will pop up the dialog.  If not, the dialog isn't popped back up.  On program start, if there are existing requests, the dialog will pop up the first time the timer expires.  I could make the timer interval for checking in with the server configurable.

Adding a "remove on song add" option sounds like a good idea.

**Comment by altere987** [comment]
Second weekend using the songbook, accept requests kept un-checking itself. I made sure I wasn't accidentally clicking it when changing windows or closing the pop-up out. Is there a time issue if someone doesn't put a song up for so long?

**Comment by coyote1357** [comment]
Actually, you just hit a bug that I found and fixed yesterday on the server side.  When you enable a venue, it's supposed to automatically disable your other venues (if you have any).  I botched the SQL query and it was disabling ALL other venues, not just the ones belonging to the user, when they enabled one of their venues.  You and I were basically fighting over having our venues enabled. LOL  Every time you enabled yours, it disabled mine.  Then I would re-enable mine and disable yours.  Ad nauseum.  It had happened very occasionally before, but not enough for me to put a priority on tracking it down until the last couple weekends.

**Comment by coyote1357** [comment]
Oh, and in the most recent version you can set the check interval under network settings.  You can also disable popping up the request dialog on new requests and there's a requests button on the main program window that will flash and show the number of requests you have when you have outstanding requests.  There's also an option to automatically remove the requests upon adding the songs to a singer's queue.

**Comment by altere987** [comment]
I won't have time to test this in the next week or so, but will the box remain the last status user selected?
 Always checked or unchecked, depending on what I've selected the last time.

**Comment by coyote1357** [comment]
That's correct.  Should stay the same until you change it
