### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by vipermetcaff** [OpenKJ/OpenKJ#38]
Incoming request button on the side bar next to the break music button and have it open to the incoming request window

**Comment by vipermetcaff** [comment]
here is another idea i had is there anyway to pull the data from  the remote database right now ive pulled it from the sqllite database
![song book](https://user-images.githubusercontent.com/6171564/34656504-51e7813a-f3d8-11e7-9c0a-9ec8bde50490.png)

**Comment by coyote1357** [comment]
The side bar is a QTabWidget and can't contain buttons, it only switches between tab widget contents.

A change with the ability to export the DB as a CSV file will be released soon, from the karaoke db management dialog.  There are no plans to be able to export from the songbook site's DB, but the data contained there is just a subset of the data contained in the CSV export feature.

**Comment by coyote1357** [comment]
1.1.66 adds a CSV export function to the DB dialog in OpenKJ

**Comment by vipermetcaff** [comment]
is there anyway to get an html export im having a hard time getting csv to output to html
