### ISSUE TITLE
id tags

### ISSUE THREAD

**Issue by vipermetcaff** [OpenKJ/OpenKJ#39]
make the id tag From the file name Like artist title  and disk id
file name 
Bill Haley & The Comets - See You Later Alligator
for video files that dont have id tag in them

**Comment by coyote1357** [comment]
I'm not sure what you're wanting to accomplish here... When you say " id tag" are you talking about the songid/discid? Making up a discid for a track that doesn't have one doesn't really gain you anything in the software.

Is this something you're using from an export of the db in a songbook or something?

**Comment by vipermetcaff** [comment]
you got me straightened Out thanks
