### ISSUE TITLE
Useful Tips for Installing on Ubuntu 16.04

### ISSUE THREAD

**Issue by henry74** [OpenKJ/OpenKJ#4]
This was pretty painful to get it to compile on Ubuntu 16.04 so I'm posting here to help others.

```
sudo apt install qt5-qmake
sudo apt install qt5-multimedia
sudo apt install libqt5svg5-dev
```
In a terminal switch to the OpenKJ/OpenKJ directory in the repository.
```
/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
make
```
Suggest installing and using checkinstall to create a .deb file
```
sudo checkinstall
```
Install the .deb file.

**Comment by coyote1357** [comment]
I've added your notes to the readme.  Thanks for sharing!

**Comment by johnmain** [comment]
The command sudo apt install qt5-multimedia didn't work.  I installed via the following:

I found that the package needed is qtmultimedia5-dev

**Comment by coyote1357** [comment]
Glad you figured it out.  I'm a RHEL/Fedora guy and am not really familiar with the Debian/Ubuntu world.  Which made figuring out how to get the necessary packages installed on Travis CI to get it to build an adventure, heh.

**Comment by johnmain** [comment]
What do you use for ripping Karaoke Disks?

**Comment by coyote1357** [comment]
I used to use cdgtools to do it, and some Windows program before that (the name escapes me), but I haven't bought a physical CD+G disc in a pretty long time.  These days I just buy and download tracks from karaokeversion.com, sunflykaraoke.us or karaoke.net, rename them appropriately, and toss them into my collection.  I usually use karaokeversion.com.  I can buy there, download, rename and move (with a script I wrote), and import the song in under a minute during my show.  Makes the singers pretty happy. :)

**Comment by coyote1357** [comment]
I managed to get continuous packaging setup over at https://packagecloud.io/OpenKJ/OpenKJ with packages for Ubuntu Trusty, Debian Jessie, Fedora 25, and RHEL7/CentOS7.   They are building successfully but haven't been tested, so if someone wants to grab them and give it a whirl, let me know whether they work or not and if they're missing any dependencies.

**Comment by coyote1357** [comment]
Dropped Trusty due to newer versions of OpenKJ requiring a newer version of gstreamer1 than ship with it.    Now building binary packages for 16.04 and 17.04 on the Ubuntu side and putting them out at https://packagecloud.io/OpenKJ/OpenKJ.  If you try the packages, please let me know whether it works or not.
