### ISSUE TITLE
Feature Request: Auto Updater

### ISSUE THREAD

**Issue by karaokeniagara** [OpenKJ/OpenKJ#42]
The ability to check for new version upon starting the program (Having a Popup say "New update available Click here to download" or even a "Check for Updates" button within the top of the program.

**Comment by coyote1357** [comment]
An update check has been added to the program 1.1.90.  It doesn't auto update, but it checks for updates on startup and pops up a notification with a link to the downloads page if a newer version is available.  At some point in the future I'll add the ability to download and install from inside the program itself, but this should work for now.
