### ISSUE TITLE
Singer-less tracks disappear from playlist as soon as song is added to a "Singer"

### ISSUE THREAD

**Issue by karaokeniagara** [OpenKJ/OpenKJ#43]
when you drag a song directly to playlist (No Singer) it displays there in the playlist along with many others no probs,  but when you create a new singer and add song to new singer. all the singer-less tracks disappear.

If you delete the singer. the singer-less tracks re-appear.

**Comment by coyote1357** [comment]
It's a bug that it was even possible to add songs without them being assigned to a singer.  I'll modify the code to reject drops w/o a selected singer and to warn the user when they try it.

**Comment by coyote1357** [comment]
1.1.90 prevents users from dragging to the queue w/o a selected singer and warns them if they try to do so.
