### ISSUE TITLE
Auto remove "played" track from playlist.

### ISSUE THREAD

**Issue by karaokeniagara** [OpenKJ/OpenKJ#44]
Have to manually delete the song after played or it stays in list
if there is a way to have it remove after 15 seconds would be perfect or just auto remove from playlist after played.

**Comment by frogonwheels** [comment]
@coyote1357 - I think it would be worth considering keeping the currently playing song displayed somehow if this option was selected.  Currently the playing song is crossed off - but maybe it would be better displaying an icon against it and NOT crossing it out? I guess you always have the information under the preview window.
