### ISSUE TITLE
Regulars Search

### ISSUE THREAD

**Issue by altere987** [OpenKJ/OpenKJ#57]
Feature request: search option for regular singers

**Comment by coyote1357** [comment]
Can you elaborate on what you mean?

**Comment by altere987** [comment]
Karaoke -> Regulars 

You can scroll up/down and add your regulars to your rotation, a search would be useful for this as this list can grow quite large.

**Comment by coyote1357** [comment]
Good idea.  Will add after the current feature freeze is over and I get the v1.2 stable release out.

**Comment by altere987** [comment]
I haven't seen this added but would also like to request in addition to a Regular search, to be able to search through a singers songs once they are added in the rotation.

Additionally, I am aware I can click on a name/artist/song and press a letter and that's what I've been doing so far. The issue is when you have so many regulars where their first name starts with 'G', same thing for songs.

**Comment by backstagekaraoke** [comment]
This has been addressed in the recent new Singer History and Regular module update in 1.8.4 and above.
