### ISSUE TITLE
song book Could This Be implimented

### ISSUE THREAD

**Issue by vipermetcaff** [OpenKJ/OpenKJ#59]
![untitled](https://user-images.githubusercontent.com/6171564/35179928-ddba9e26-fd61-11e7-8d82-4c15f6d742c1.png)

**Comment by coyote1357** [comment]
I'm not sure what you're asking for.... For the search box to stay up with the results?

**Comment by vipermetcaff** [comment]
adding the songs so you can find a song That they have on there computer  i pulled the file from the songbook pdf was wondering if there is a way to convert the song book to html some browsers dont display pdf at all

**Comment by coyote1357** [comment]
There's a plan to release a self-hosted songbook website.  But that's separate from the PDF generator.  The PDF generator is only really intended for those who want to print physical books out.

**Comment by vipermetcaff** [comment]
ok Cool
