### ISSUE TITLE
Let the user know when the API key is wrong

### ISSUE THREAD

**Issue by generalredneck** [OpenKJ/OpenKJ#69]
When using the "Incoming Requests" feature, I accidently had a space at the end of my key because yeah... I copy and pasted the thing... 
THe Updating request server song database dialog went through it's thing and then sat at 95% for freaking ever (hour and a half?). Also my venues would never refresh. That's how I finally figured out there must be something up...

Any way there can be some error handling slapped around this?

**Comment by coyote1357** [comment]
It's an oversight that it's not warning people.  I'll definitely add a
validation and warning.  Thanks for the feedback!

**Comment by coyote1357** [comment]
Finally got around to this.  There is now a test button in the request server settings that will validate the connection settings and API key.
