### ISSUE TITLE
Songbook api open sourced?

### ISSUE THREAD

**Issue by generalredneck** [OpenKJ/OpenKJ#70]
I probably could read the code and recreate it but do you think you are going to open source the songbook server too? I see you already thought ahead and added the variable base url. It woujld be handy to recreate a system that integrated with other content and showed singer stats per venue and what not. I do php/web dev as my day job so I think the site could benefit from several featured I have in mind.

**Comment by coyote1357** [comment]
I plan on releasing a single venue standalone request server that people can host themselves.  It will be open source and live here on GitHub.  It won't be identical to the hosted version that I'm currently serving up, as that will eventually be a paid service, but I don't plan on crippling the standalone version in any way aside from stripping out the multi-kj/venue bits and making it use sqlite for simplicity rather then requiring a mySQL or MariaDB backend.

**Comment by coyote1357** [comment]
Just put up a basic php implementation of a standalone request server.  As a pro, it should be pretty self explanatory to you.  Feel free to submit any fixes or improvements you'd like to share. :) 
https://github.com/OpenKJ/StandaloneRequestServer

**Comment by generalredneck** [comment]
Sweet. Yes it's very straight forward. You developed it very rapidly it appears so it's done in a very "old school" fashion. The plus to this is it may possibly be very performant. The down side is it may become difficult to maintain and alter. 2 thoughts... 1) the api library could be separate from the web interface. 2) see if we can implement some view control so that it will be easier to modify the markup for the website front end.

I'll fork and give it a shot.

**Comment by coyote1357** [comment]
Awesome. 🙂  And yeah, old school makes sense since this is the first time I've dusted off my php skills to write something from scratch in probably a decade or more. LOL

**Comment by karaokeniagara** [comment]
This is exciting! An Open source server based karaoke software with many pro features. Looking forward to seeing the latest and greatest server/client enhancements for OpenKJ.

**Comment by kevin71246** [comment]
Any chance this work was every completed? (Allowing a standalone webserver for song requests from users). Thanks & nice job! I just got this and am testing it out for home use...

**Comment by generalredneck** [comment]
There are a couple if options at this moment https://github.com/OpenKJ/StandaloneRequestServer and https://git.drupalcode.org/sandbox/generalredneck-3017533

**Comment by richiela** [comment]
@generalredneck did you ever fork this?  Also has anyone ever dockerize this?  New to the software and looking for options before I go rewriting/reworking a bunch of things...

**Comment by generalredneck** [comment]
Didn't fork it. Rebuilt it for drupal. I've got some fixes in the works for this exact project but it's not anything revolutionary.

**Comment by generalredneck** [comment]
@backstagekaraoke FYI. I'm pretty sure that Issac publishing https://github.com/OpenKJ/StandaloneRequestServer solved this issue.

**Comment by backstagekaraoke** [comment]
OK i'll close this one off then
