### ISSUE TITLE
Song database update to address deleted or changed files

### ISSUE THREAD

**Issue by generalredneck** [OpenKJ/OpenKJ#71]
When I do a song database update... it doesn't pick out deleted files. Nuking it removes my regulars... I recently weeded out  bad directory... any suggestions?

**Comment by coyote1357** [comment]
Right now the best option is to export your regulars, nuke and re-import the db, then import the regulars back in.

Making db update handle removed or moved songs gracefully is something I plan on adding during the 1.3.x development cycle.

**Comment by backstagekaraoke** [comment]
Has been discussed a number of times between Isaac and myself, and it's absolutely on the work list.
