### ISSUE TITLE
Song tagging and meta data search 

### ISSUE THREAD

**Issue by generalredneck** [OpenKJ/OpenKJ#72]
A few things here... would be nice to pull from mp3 meta data... Nice to Have though...would would really help is for the song book api and/or the openkj app allow you to track, update, and search meta data on songs. Examples may be tags/categories such as "disney", showtunes... or genre like rap... I could totally see these being used in a faceted search in solr for the songbook request site... and just plain helpful for me.

**Comment by coyote1357** [comment]
Reading and manipulating the metadata tags would definitely be on the hosting software side, and wouldn't be terribly difficult to integrate.  Songbook side could then be expanded to include them in some way.  One caveat here is that, from what I've seen, the tagging on most mp3g purchased files tends to be very basic, so this would only have much utility for those who do the tagging themselves.

**Comment by backstagekaraoke** [comment]
when the upcoming 'Tags' system is implemented it may very well solve this problem anyway. So I'll close this off and you once tags is implemented, see how it goes.
