### ISSUE TITLE
database

### ISSUE THREAD

**Issue by vipermetcaff** [OpenKJ/OpenKJ#73]
@coyote1357  there anyway to have  the Openkj database in the Openkj folder instead of being in the C:\Users\.............\AppData\Local\OpenKJ in case you have to redo your windows install
and is there any way to store the custom message in int database

**Comment by duringleaves** [comment]
I'd love to keep songs, app, and database all on the same portable drive so I can setup at anyone's computer.  Being able to customize the path to the database and settings alongside the app package would allow for that portability

**Comment by backstagekaraoke** [comment]
There is a number of reasons why having the database on a separate partition or external drive would not really work. There is much bigger ticket items to focus on right now,
