### ISSUE TITLE
Minimum requirements?

### ISSUE THREAD

**Issue by mpkogli** [OpenKJ/OpenKJ#78]
Nice project! What are the minimum hardware requirements in order to run this? Would it run on a newer Raspberry Pi, for example?

**Comment by coyote1357** [comment]
I'm honestly not sure, I haven't tested it on any low powered devices. I know from emails from a user that it doesn't work well on old single core Intel Atom processor based laptops under Windows, but that doesn't necessarily mean it won't work under Linux on a Pi. The biggest likely problem on the Pi is the limited amount of RAM available.  All I can really say is give it a shot and see if it works. :)
