### ISSUE TITLE
Ticker on unstable builds

### ISSUE THREAD

**Issue by crbunch** [OpenKJ/OpenKJ#86]
Just want to let you know I like the new theme but the Ticker at the bottom of the unstable builds scrolls a bunch of gibberish on the ticker.

**Comment by coyote1357** [comment]
I'm unable to duplicate this in my test environments.  What OS are you using it on.  And what font are is your ticker currently set to use?

**Comment by crbunch** [comment]
My apologies after looking through the ticker setting I found that it was user error and I accidentally moved the slider on the speed to the far left.
