### ISSUE TITLE
Not compatible with Qt 5.11?

### ISSUE THREAD

**Issue by AThomsen** [OpenKJ/OpenKJ#93]
Build from source on Arch Linux (bleeding edge distro).

The program seems to run fine, but the database is never filled.
Terminal outputs lots of

~~~
QSqlDatabasePrivate::database: requested database does not belong to the calling thread.
QSqlQuery::exec: database not open
QSqlDatabasePrivate::database: requested database does not belong to the calling thread.
QSqlQuery::prepare: database not open
QSqlDatabasePrivate::database: requested database does not belong to the calling thread.
QSqlQuery::exec: database not open
~~~

I may be related to some changes in the latest Qt 5.11: https://bugreports.qt.io/browse/QTBUG-216

**Comment by frogonwheels** [comment]
Just a quick look, and being a newcomer to Qt, I think there are a couple of major issues that need to be sorted with the code.  From reading your very helpful link to the bug report, the problems are there in previous version, it's just that the error in QT 5.11 is the exact reason the error is there... ie, the code shouldn't be accessing the SQLight database from different threads.

I think there are 2 possible solutions:  1st is create a new database connection for each of the 3? threads (Main UI, Database update & website monitor), and second is to synchronise all requests and responses into the main UI thread.  The use-cases of these threads might make the second one the preferable... just queue updates from one thread into the main Ui thread.

**Comment by coyote1357** [comment]
I think this should be fixed now. Y'all were correct on the changes in Qt 5.11 breaking it.  The db update thread now creates a new connection rather than using the default program wide one.

**Comment by johnmain** [comment]
@coyote1357 
did the Ubuntu build get updated?  I am attempting to run on Linux Mint 19 (Ubuntu 18.04 based)
and am getting a similar issue:

```
qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
Initial volumes - K:  50  BM:  50
QSqlDatabase: QSQLITE driver not loaded
QSqlDatabase: available drivers
```:

**Comment by coyote1357** [comment]
The Qt 5.11 problems are fixed for real now, heh.  I wound up having to move the db update code back into the main thread because of db locking issues btwn threads w/ the QSqlTableModel's creating locks for some stupid reason.  Small db update speed hit, but nothing terrible.

On the SQLITE driver not loaded error, that's something completely different.  I have no idea why the distro wouldn't have the QSQLITE driver included.  Maybe I'm missing a Qt deb dependency that's present on vanilla Ubuntu but not loaded on Mint for some reason.

**Comment by johnmain** [comment]
@coyote1357 
I manually installed libqt5sql5-sqlite and OpenKJ now opens.  Wouldn't this be a dependency on the OpenKJ Deb?

**Comment by coyote1357** [comment]
It apparently should be.  I'll add it as a dependency.  When I tested on vanilla Ubuntu when initially setting the dependencies and such it worked, so it was either present by default or wasn't split out into its own package at that point.  I don't ever use Ubuntu personally, I'm a Fedora/RHEL guy, so I tend to not notice these things until someone reports them ;)

**Comment by coyote1357** [comment]
Closing this as it should be fixed.  Feel free to reopen if you still have any issues.
