### ISSUE TITLE
Feature request - Separate manageable karaoke song DB per venue

### ISSUE THREAD

**Issue by vaccinemedia** [OpenKJ/OpenKJ#94]
It would be cool to be able to manually manage karaoke tracks which are available and have multiple databases to manage, one per venue i.e. delete tracks from the DB by selecting the track and hitting the delete key.

Scenario: You are a KJ and have regular shows at two different venues. One is in the Gay Village and one is a Rock and Alternative bar. You have a large set of karaoke tracks spanning several genres and don't particularly mind all of the tracks being available in the any song goes village, however in the alternative bar you don't want people to see that you have Steps, Justin Bieber or Take That.

I could see an editable "playlist" of karaoke tracks coming in handy here. You could create a venue which would have a blank database of karaoke tracks. You then scan the folder and this would add all the tracks. Next step would be to perform a search for e.g. Take That and from the results select all the tracks and hit the delete key. Do this as many times as needed and then sync the DB to opensongbook.

You could then have several venues in opensongbook each with different songs available on the server and regulars in the local DB.

Any thoughts on this?

**Comment by backstagekaraoke** [comment]
I really don't understand why simply having certain songs or artists appear in the songlist is an issue? They obviously aren't going to sing those songs ... and they will only be searching for songs or artists they want right?

The current iteration of the OpenKJ Songbook platform, does save songlists on a per venue basis ... however it only saves one version. So when you update it for that venue, it simply overwrites the previous one. This is good, as it makes sure that venues DB is the latest one, and also if you have multiple hosts, each with their own rig possibly doing the same venue, they can simply do an Update DB before their show, and the patrons get that host's library.

For your scenario, right now, what you COULD do on your host machine, is create two versions of your library .e.g. 
\KaraokeLibary\Venue-GayVillage
\KaraokeLibary\Venue-RockAlternative

Then just put whichever songs you want in each of the libraries, and then before each show, you will need to do a 'Clear DB' then add in the path you want for the library, and then run Update All. The reason for this is that OpenKJ doesn't currently remove existing tracks from its DB when the files have been removed - see #148 .

So essentially you are just 'rebuilding' your library for each venue each time, then pushing that update to OKJ songbook venue.

The OpenKJ songbook agent does have an Import CSV option, which would allow you to just create a CSV and use that, however thats a bit pointless as you don't want to be receiving the requests in the Songbook Agent software, only to have to manually enter the singers into OpenKJ.

**Comment by coyote1357** [comment]
This sort-of exists now with the multi-rig account stuff on Songbook, but it would require an additional entitlement.  Reach out to me if it's something you still need/want, and we'll talk.
