### ISSUE TITLE
Feature Request > Touch friendly buttons including popup keyboard

### ISSUE THREAD

**Issue by karaokeniagara** [OpenKJ/OpenKJ#96]
**Feature Request** > Touch friendly buttons including popup keyboard.
Is it possible to make a TOUCH SCREEN KARAOKE theme within OpenKJ?

1) Make the Keychanger buttons larger (Touch friendly)
2) Add an onscreen keyboard (permanent or popup) or even a "show keyboard" button

**Comment by backstagekaraoke** [comment]
There has been a recent size increase to the Ui buttons, however it’s not to the level of being ‘touch friendly’.
There is much bigger ticket items to focus on, so we will not be looking into this any further at this time.
