### ISSUE TITLE
auto play not working 

### ISSUE THREAD

**Issue by apiontek** [OpenKJ/OpenKJ#97]
I'm in 1.3.78 64bit on Windows (also tested 1.3.78 on linux (Ubuntu 18.04 in KDE Plasma)

Auto play isn't working. I tried different delays (30 seconds, 1 second, 0 seconds). When a song is playing, and finishes, it just stops. Nothing happens. Let me know what more info I can provide to assist in debugging / troubleshooting this, thanks!

**Comment by coyote1357** [comment]
In the current version, I was just using this to do a burn in test last night on Windows 10 64bit and Linux (Fedora 28 64bit) and it was working okay.  Loaded up two singers with 80 songs each and kicked it off in auto-play mode.  Ran through all 160 songs...  Can you verify that this is still an issue for you in the current version?

**Comment by vipermetcaff** [comment]
check to make sure the delay
![autoplay](https://user-images.githubusercontent.com/6171564/46920858-945bb800-cfb1-11e8-8574-519692c6c191.png)

**Comment by vipermetcaff** [comment]
auto play isnt working 1.5.7 unstable  or 141 stable

**Comment by apiontek** [comment]
I can confirm that, for me, autoplay is working on 1.4.1 stable on Linux (Ubuntu 18.04, Gnome)

I will test in Windows later today. Thanks!
