### ISSUE TITLE
Feature request: skip song keyboard shortcut

### ISSUE THREAD

**Issue by apiontek** [OpenKJ/OpenKJ#98]
I'm testing 1.3.78 on Windows and Ubuntu, and love it so far, thanks much for working on this software.

Although autoplay isn't working for me and I opened a separate ticket, when that's fixed, I would also love to have the ability to quickly skip a currently playing song. My wife & I have done karaoke at family gatherings for the past few years, mainly using Karma on Windows, and people invariably regret a choice, or aren't around.

There doesn't seem to be a quick & easy way of jumping ahead to the next singer/song in the queue, and a keyboard shortcut & button for that would be much appreciated.

**Comment by backstagekaraoke** [comment]
A custom keyboard shortcut module has now been introduced now from v1.8.4 onwards.
