### ISSUE TITLE
Singer name column missing in the requests window

### ISSUE THREAD

**Issue by vaccinemedia** [OpenKJ/OpenKJ#99]
The singer name column appears to have disappeared since the latest stable release.
![screen shot 2018-07-14 at 20 42 21](https://user-images.githubusercontent.com/10465885/43685403-74736a1c-98aa-11e8-9a07-39fb9777b5ac.png)

**Comment by vaccinemedia** [comment]
It's there until the commits made on the 6th of July so somewhere between 1.3.71 and 1.3.74 it happened

**Comment by coyote1357** [comment]
Finally figured out what was going on here.  I was unable to duplicate it until I cleared my settings file and then saw the problem.  1.3.103 is building now and should be available within 15 mins or so on all platforms.  I apologize for it taking me so long to resolve this.
